FROM ghcr.io/mr-pmillz/alpine-bash-tini:latest

ARG TARGETPLATFORM

COPY entrypoint.sh /entrypoint.sh
COPY $TARGETPLATFORM/gogatoz /usr/local/bin/gogatoz
RUN chmod +x /entrypoint.sh /usr/local/bin/gogatoz

ENTRYPOINT ["/sbin/tini", "--", "/entrypoint.sh"]
