package cmd

import (
	"bytes"
	"strings"
	"testing"
)

func TestAttack_PayloadOnly_MissingPayload(t *testing.T) {
	// Ensure clean state
	oldOnly, oldPayload := atkPayloadOnly, atkPayload
	defer func() { atkPayloadOnly, atkPayload = oldOnly, oldPayload }()
	atkPayloadOnly = true
	atkPayload = ""
	var buf bytes.Buffer
	attackCmd.SetOut(&buf)
	if err := attackCmd.RunE(attackCmd, nil); err == nil || !strings.Contains(err.Error(), "--payload is required") {
		t.Fatalf("expected missing --payload error, got %v", err)
	}
}

func TestAttack_PayloadOnly_RORShell(t *testing.T) {
	// Configure payload-only mode for ror-shell
	oldOnly, oldPayload, oldCmd, oldTags, oldManual := atkPayloadOnly, atkPayload, atkCmd, atkTags, atkManual
	defer func() {
		atkPayloadOnly, atkPayload, atkCmd, atkTags, atkManual = oldOnly, oldPayload, oldCmd, oldTags, oldManual
	}()
	atkPayloadOnly = true
	atkPayload = "ror-shell"
	atkCmd = "echo hi"
	atkTags = "self-hosted, amd64"
	atkManual = true
	// Capture output
	var buf bytes.Buffer
	attackCmd.SetOut(&buf)
	if err := attackCmd.RunE(attackCmd, nil); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, "Auto-generated by GoGatoZ") || !strings.Contains(out, "script:") {
		t.Fatalf("unexpected payload output: %s", out)
	}
	if !strings.Contains(out, "rules:") { // manual rule added
		t.Fatalf("expected manual rule in payload: %s", out)
	}
}

func TestAttack_PayloadOnly_PwnRequest(t *testing.T) {
	oldOnly, oldPayload, oldRegex := atkPayloadOnly, atkPayload, atkTargetBranchRegex
	defer func() { atkPayloadOnly, atkPayload, atkTargetBranchRegex = oldOnly, oldPayload, oldRegex }()
	atkPayloadOnly = true
	atkPayload = "pwn-request"
	atkTargetBranchRegex = "main|prod"
	var buf bytes.Buffer
	attackCmd.SetOut(&buf)
	if err := attackCmd.RunE(attackCmd, nil); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, "merge_request_event") {
		t.Fatalf("expected MR condition in pwn-request payload: %s", out)
	}
}
