package report

import (
	"fmt"
	"strings"

	"github.com/mr-pmillz/gogatoz/pkg/analyze"
)

const mrCommentIdentifier = "<!-- GoGatoZ Compliance Comment -->"

// BuildMRCommentBody generates a Markdown comment body for a GitLab merge request.
func BuildMRCommentBody(rep Report, score *analyze.ScoreResult) string {
	var b strings.Builder

	b.WriteString(mrCommentIdentifier)
	b.WriteString("\n\n")

	if score != nil {
		fmt.Fprintf(&b, "## GoGatoZ Security Score: %s (%0.0f pts)\n\n", score.Score, score.FinalPoints)
	} else {
		b.WriteString("## GoGatoZ Security Scan Results\n\n")
	}

	b.WriteString("| Severity | Count |\n")
	b.WriteString("|----------|-------|\n")
	fmt.Fprintf(&b, "| Critical | %d |\n", rep.Summary.BySeverityStr["CRITICAL"])
	fmt.Fprintf(&b, "| High | %d |\n", rep.Summary.BySeverityStr["HIGH"])
	fmt.Fprintf(&b, "| Medium | %d |\n", rep.Summary.BySeverityStr["MEDIUM"])
	fmt.Fprintf(&b, "| Low | %d |\n", rep.Summary.BySeverityStr["LOW"])
	fmt.Fprintf(&b, "| Info | %d |\n", rep.Summary.BySeverityStr["INFORMATIONAL"])
	fmt.Fprintf(&b, "| **Total** | **%d** |\n\n", rep.Summary.Findings)

	if rep.Summary.Exploitable > 0 {
		fmt.Fprintf(&b, "**Exploitable projects**: %d\n\n", rep.Summary.Exploitable)
	}

	maxProjects := min(len(rep.Projects), 10)
	if maxProjects > 0 {
		b.WriteString("<details>\n<summary>Top findings by project</summary>\n\n")
		b.WriteString("| Project | Findings | Critical | High | Medium |\n")
		b.WriteString("|---------|----------|----------|------|--------|\n")
		for i := 0; i < maxProjects; i++ {
			pv := rep.Projects[i]
			fmt.Fprintf(&b, "| %s | %d | %d | %d | %d |\n",
				pv.Project.ProjectPathWithNS, pv.FindingCount, pv.Critical, pv.High, pv.Medium)
		}
		b.WriteString("\n</details>\n\n")
	}

	if score != nil && len(score.CodeLosses) > 0 {
		b.WriteString("<details>\n<summary>Score breakdown</summary>\n\n")
		b.WriteString("| Finding | Severity | Count | Loss |\n")
		b.WriteString("|---------|----------|-------|------|\n")
		maxLosses := min(len(score.CodeLosses), 15)
		for i := 0; i < maxLosses; i++ {
			cl := score.CodeLosses[i]
			fmt.Fprintf(&b, "| %s | %s | %d | -%.1f |\n", cl.Code, cl.Severity, cl.Count, cl.CappedLoss)
		}
		fmt.Fprintf(&b, "\n**Raw**: %.1f / **Final**: %.1f (%s)\n", score.RawPoints, score.FinalPoints, score.Score)
		if score.CriticalMalusApplied {
			b.WriteString("\nCritical finding detected - score capped at E grade.\n")
		}
		b.WriteString("\n</details>\n\n")
	}

	b.WriteString("---\n*Generated by [GoGatoZ](https://github.com/mr-pmillz/gogatoz)*\n")
	return b.String()
}

// MRCommentIdentifier returns the HTML comment used to find the GoGatoZ
// comment in merge request notes.
func MRCommentIdentifier() string {
	return mrCommentIdentifier
}
